### ISSUE TITLE
UI fix in Cart `-` & `+` buttons

### ISSUE THREAD

**Issue by Disha-Hati** [pooranjoyb/popShop#1]
The Cart Page looks non-functional. I can't add items, neither I can remove.  It has a static value of 8 items. I can make it functional.
I'm GSSOC'24 contributor,Can you please assign this issue to me?

**Comment by Disha-Hati** [comment]
Thank you @pooranjoyb 
Yeah sure, while fixing the cart page, I'll remove the up and down arrows as well
Will those be 2 different issues and PR? or I'll add both in this itself?

**Comment by pooranjoyb** [comment]
> Thank you @pooranjoyb Yeah sure, while fixing the cart page, I'll remove the up and down arrows as well Will those be 2 different issues and PR? or I'll add both in this itself?

Nope, the issue that you mentioned will be raised and worked upon later. Probably in a day or two. You can just rename the issue title to `UI Fix for Button in Cart` @Disha-Hati

**Comment by Disha-Hati** [comment]
Okay Sure. Thank You

**Comment by Disha-Hati** [comment]
Hi @pooranjoyb 
I tried finding solution to disable arrow spinner for tailwind CSS , none of them is a one stop solution for all browsers or versions.
So what I suggest is 
a. keeping the input type="text" and adding regex pattern to allow only numbers. 
The code would look like
``` 
<input type="text" className="" placeholder="1" pattern='^[0-9]$' /> 
```
Solution:
![image](https://github.com/pooranjoyb/popShop/assets/70029959/12ce0ef1-1052-4a7e-bb07-28cc4075c220)

b. Otherwise, one more solution could be using State variables and updating counter when clicking + / - button unless it's just UI application . Then later updating with redux store. 

Just let me know if any of my solution sounds good to you? I'll create changes accordingly.
Thank You

**Comment by pooranjoyb** [comment]
Yes this seems okay! Go ahead👍 @Disha-Hati

**Comment by Disha-Hati** [comment]
> Yes this seems okay! Go ahead👍 @Disha-Hati

The regex one works? So I am going with option (a)

**Comment by Disha-Hati** [comment]
Fixed the issue , created PR to dev , Can you please approve my PR? https://github.com/pooranjoyb/popShop/pull/6
![image](https://github.com/pooranjoyb/popShop/assets/70029959/96e5ceef-82bc-4e2f-871c-c1a2b3b5f52e)
