### ISSUE TITLE
Implement forget password

### ISSUE THREAD

**Issue by Niharika0104** [pooranjoyb/popShop#10]
#### Description:
The application currently lacks the "Forgot Password" feature, which is crucial for user account recovery. This issue is to implement the necessary pages and functionality required for the "Forgot Password" feature.

#### Tasks:
1. **Create Forgot Password Page:** Develop a new page or modal for the "Forgot Password" functionality.
   - **Steps to Implement:**
     1. Design the user interface for entering email addresses for password reset requests.
     2. Implement the frontend components for the Forgot Password page/modal.
   - **Expected Behavior:** Users should be able to access the Forgot Password page/modal to initiate the password reset process.

2. **Backend Logic for Password Reset:** Develop backend logic to handle password reset requests and send reset instructions to the user's email.
   - **Steps to Implement:**
     1. Define API endpoints or backend routes to handle password reset requests.
     2. Implement logic to generate and store password reset tokens securely.
     3. Integrate with email services to send password reset instructions to users.
   - **Expected Behavior:** Upon submitting a password reset request, users should receive instructions on how to reset their passwords via email.

**Comment by pooranjoyb** [comment]
Hii @Niharika0104 one issue at a time, hehe :)))
Will assign once you finish up the other one 👍🏼

**Comment by Niharika0104** [comment]
Sure I will try to complete it the other issue by  today

**Comment by AryanAg08** [comment]
Hii, I want to work on this issue!! Can you assign me this issue ?

**Comment by pooranjoyb** [comment]
> Hii, I want to work on this issue!! Can you assign me this issue ?

Go for it @AryanAg08 🚀

**Comment by AryanAg08** [comment]
Okkk thanks

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀

**Comment by AryanAg08** [comment]
It has been already assigned to me !!

**Comment by pooranjoyb** [comment]
> It has been already assigned to me !!

Hii @AryanAg08 , DM me in Discord if you wanted to have a look on the supabase DB after the UI part is done. 
Anyways, whats the update of the UI part? Is the `Forget Password` component done?

**Comment by AryanAg08** [comment]
hii @pooranjoyb , I have started with the work. But due to my semester end exams I had to stop working on it. But will get it done as soon as possible? Also Can you share me your discordId so I can contact you ?

**Comment by pooranjoyb** [comment]
> hii @pooranjoyb , I have started with the work. But due to my semester end exams I had to stop working on it. But will get it done as soon as possible? Also Can you share me your discordId so I can contact you ?

Pooranjoy#1868

**Comment by AryanAg08** [comment]
okk!! Thanks for understanding. I will get back to you as soon as possible

**Comment by IP80808080** [comment]
> > hii @pooranjoyb , I have started with the work. But due to my semester end exams I had to stop working on it. But will get it done as soon as possible? Also Can you share me your discordId so I can contact you ?
> 
> No issues, you can work on other issues as well. Take your time :) Assigning the issue to @IP80808080 based on FCFS basis.
> 
> Connect me on discord `Pooranjoy#1868` @AryanAg08

Sorry It took me long time, my exam were ongoing, I just wanted to ask do I have to use email service of supabase or nodemailer like service for sending mail

**Comment by pooranjoyb** [comment]
Nope, as of now, just create the `schema`, validate it, and create the components. That'll do!

**Comment by IP80808080** [comment]
Hello Sir

I have submitted a pull request for issue #10, which includes a feature forgot password and schema. I kindly request you to review the pull request and any changes require ping me.
