### ISSUE TITLE
[FEATURE] Add About Us Page

### ISSUE THREAD

**Issue by DurgaPrasad-R** [pooranjoyb/popShop#100]
The About us link in the footer section is taking us back to the login page, though we are logged in. This issue is regarding the addition of an About Us page to the project that briefly describes the overview of what the website does.
Screenshots:
![image](https://github.com/pooranjoyb/popShop/assets/111352968/f3027ac5-dcb1-4c9d-bbb5-70f30f04b05e)
![image](https://github.com/pooranjoyb/popShop/assets/111352968/c8e551b5-7709-415b-b833-6a0317d358cf)

Please assign me this issue under GSSOC'24.

**Comment by pooranjoyb** [comment]
Congratulations, @DurgaPrasad-R! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Drop the Figma here :) @DurgaPrasad-R

**Comment by DurgaPrasad-R** [comment]
Hi @pooranjoyb, I'm happy to have received feedback from you. Please go through the Figma design at the link below:
https://www.figma.com/design/4pMl5Anv4Ci4Kvyp9ulnzq/PopShop.com-AboutUsPage?node-id=0%3A1&t=ttxdv7AN3mX5c7qa-1
I'm open to discussions if you've any other ideas or advices.
Thank You!

**Comment by pooranjoyb** [comment]
> Hi @pooranjoyb, I'm happy to have received feedback from you. Please go through the Figma design at the link below: https://www.figma.com/design/4pMl5Anv4Ci4Kvyp9ulnzq/PopShop.com-AboutUsPage?node-id=0%3A1&t=ttxdv7AN3mX5c7qa-1 I'm open to discussions if you've any other ideas or advices. Thank You!

We would really want a minimalist and theme-specific UI for the same. Show github Contributors in the website too. 

@Mahitej28 Will review and guide you :) 
Happy Coding 🚀

**Comment by DurgaPrasad-R** [comment]
@pooranjoyb I didn't get you. Do you want me to add the contributors section in the About Us page?

**Comment by pooranjoyb** [comment]
> @pooranjoyb I didn't get you. Do you want me to add the contributors section in the About Us page?

Show the contributors display pictures in the contributors section. @DurgaPrasad-R

**Comment by DurgaPrasad-R** [comment]
@pooranjoyb I would start working on the feature once you confirm the contributors section as shown in the Figma file.

**Comment by pooranjoyb** [comment]
Sorry to say, everything's good, but the UI doesn't seem professional dude. If you wanna maintain the theme you can go ahead, else you can drop it and go for another issues. 
Happy coding :) @DurgaPrasad-R

**Comment by DurgaPrasad-R** [comment]
I cannot continue this, as I am busy with others.
