### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by Nehakumari1208** [pooranjoyb/popShop#103]

**Comment by Nehakumari1208** [comment]
Assign this to me

**Comment by pooranjoyb** [comment]
Congratulations, @Nehakumari1208! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@Nehakumari1208 check #79
