### ISSUE TITLE
[FIX]: GitHub link in Contributing.md file is incorrect

### ISSUE THREAD

**Issue by DurgaPrasad-R** [pooranjoyb/popShop#106]
This issue is regarding the incorrectly mentioned GitHub link in the Contributing.md file.
Screenshot:
![image](https://github.com/pooranjoyb/popShop/assets/111352968/acbcebea-7a68-48ff-810e-733f071a63fb)

**Comment by pooranjoyb** [comment]
Congratulations, @DurgaPrasad-R! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@DurgaPrasad-R thanks for addressing the error but its not something you will be getting a gssoc level for, its really a very small issue and perhaps don't require a pr to be raised.
