### ISSUE TITLE
Add issues template

### ISSUE THREAD

**Issue by suhanipaliwal** [pooranjoyb/popShop#108]
I would like to add a issues template for this repository. I believe that having a standardised template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review issues.

Could you please assign this issue to me under GSSOC'24.

**Comment by pooranjoyb** [comment]
Congratulations, @suhanipaliwal! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@suhanipaliwal check #49
