### ISSUE TITLE
[Feature] Logo for PopShop 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#116]
### Description

Design the Logo for the Application and drop the Figma here in comments :)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by me-shweta** [comment]
@pooranjoyb Hi, I'm Shweta. 
Under GSSOC'24, I'm interested in designing the logo for PopShop. Assign me this task!

**Comment by pooranjoyb** [comment]
> @pooranjoyb Hi, I'm Shweta. 
> Under GSSOC'24, I'm interested in designing the logo for PopShop. Assign me this task!

Go Ahead Shweta, maintain theme and drop the figma jn comments oncedone! All the best! :rocket:
@me-shweta

**Comment by me-shweta** [comment]
@pooranjoyb If you don't mind, could you provide me with some references for theme ideas?

**Comment by me-shweta** [comment]
okay!
@pooranjoyb Can you tell me on what to focus more while making a logo, like clothing or something else?"

**Comment by pooranjoyb** [comment]
> okay!
> @pooranjoyb Can you tell me on what to focus more while making a logo, like clothing or something else?

Yes ig clothing will be good as of now. Although you are free to innovate.@me-shweta :rocket:

**Comment by me-shweta** [comment]
@pooranjoyb I have created some designs. Here they are.
![1](https://github.com/pooranjoyb/popShop/assets/119609866/892206d3-ee40-4ae1-85dd-68e11daa29fa)
![2](https://github.com/pooranjoyb/popShop/assets/119609866/5383e889-98fc-4256-83ee-8c910bd3a7ca)
![3](https://github.com/pooranjoyb/popShop/assets/119609866/396d10e2-8c35-42b4-8215-0a5cb6f3d4d4)
![4](https://github.com/pooranjoyb/popShop/assets/119609866/6cd6c717-c860-4f46-bf67-ab87865c92ae)
![5](https://github.com/pooranjoyb/popShop/assets/119609866/d5b57e20-81b1-475b-b5f2-799409c02b1e)
![6](https://github.com/pooranjoyb/popShop/assets/119609866/c0a43235-bcd2-46a9-b4c8-569f62c36ef8)
![7](https://github.com/pooranjoyb/popShop/assets/119609866/f7a179db-10ff-463e-9e44-034d6b944e1b)
![8](https://github.com/pooranjoyb/popShop/assets/119609866/6927a502-bd37-48c8-8660-b76a8c36ad72)
![9](https://github.com/pooranjoyb/popShop/assets/119609866/1f50652d-780b-46cc-8676-ab6212c89252)

**Let me know which design suits you best and if there are any changes you would like to make.**
Is there any tagline for PopShop?

**Comment by pooranjoyb** [comment]
Haha nice ones! I guess @Mahitej28 should take decisions on this!!!

**Comment by me-shweta** [comment]
@Mahitej28 Let me know which design suits you best and if there are any changes you would like to make.

**Comment by Mahitej28** [comment]
> @pooranjoyb I have created some designs. Here they are.
> ![1](https://github.com/pooranjoyb/popShop/assets/119609866/892206d3-ee40-4ae1-85dd-68e11daa29fa)
> ![2](https://github.com/pooranjoyb/popShop/assets/119609866/5383e889-98fc-4256-83ee-8c910bd3a7ca)
> ![3](https://github.com/pooranjoyb/popShop/assets/119609866/396d10e2-8c35-42b4-8215-0a5cb6f3d4d4)
> ![4](https://github.com/pooranjoyb/popShop/assets/119609866/6cd6c717-c860-4f46-bf67-ab87865c92ae)
> ![5](https://github.com/pooranjoyb/popShop/assets/119609866/d5b57e20-81b1-475b-b5f2-799409c02b1e)
> ![6](https://github.com/pooranjoyb/popShop/assets/119609866/c0a43235-bcd2-46a9-b4c8-569f62c36ef8)
> ![7](https://github.com/pooranjoyb/popShop/assets/119609866/f7a179db-10ff-463e-9e44-034d6b944e1b)
> ![8](https://github.com/pooranjoyb/popShop/assets/119609866/6927a502-bd37-48c8-8660-b76a8c36ad72)
> ![9](https://github.com/pooranjoyb/popShop/assets/119609866/1f50652d-780b-46cc-8676-ab6212c89252)
> 
> **Let me know which design suits you best and if there are any changes you would like to make.**
> Is there any tagline for PopShop?

Hey @me-shweta really nice designs, I would like to go ahead with the fourth one, the only thing is its a bit monochorme I suggest adding different colors to it like you did in the first one.

**Comment by me-shweta** [comment]
okay @Mahitej28 ! 
You want edits for this one .. right ?
<img width="267" alt="Capture" src="https://github.com/pooranjoyb/popShop/assets/119609866/abbc0d36-4808-4670-b33b-36ea86c09d12">

**Comment by me-shweta** [comment]
@Mahitej28 **If you are talking about this design, it can have a maximum of three color variations. I have made some changes, and this is the maximum number of color variations that can be added.** 

![4](https://github.com/pooranjoyb/popShop/assets/119609866/c1bce6d4-5a63-4739-980f-550e7eae4d56)

**Also, I have added "if you are looking for shopping bags" in the first bag design. Let me know if we can use this picture now.** 

![1](https://github.com/pooranjoyb/popShop/assets/119609866/8fa79ab9-796e-4bdc-9779-830bd9920663)

**Additionally, I made two more logo that depicts online shopping. Now, let me know your opinion on these designs.**

![2](https://github.com/pooranjoyb/popShop/assets/119609866/9431559f-fd45-4324-98c9-09cc9d851f8e)
![3](https://github.com/pooranjoyb/popShop/assets/119609866/b02d3982-8561-4555-9f4f-f404a3170e99)

**Comment by Mahitej28** [comment]
> @Mahitej28 **If you are talking about this design, it can have a maximum of three color variations. I have made some changes, and this is the maximum number of color variations that can be added.** 
> 
> ![4](https://github.com/pooranjoyb/popShop/assets/119609866/c1bce6d4-5a63-4739-980f-550e7eae4d56)
> 
> **Also, I have added "if you are looking for shopping bags" in the first bag design. Let me know if we can use this picture now.** 
> 
> ![1](https://github.com/pooranjoyb/popShop/assets/119609866/8fa79ab9-796e-4bdc-9779-830bd9920663)
> 
> **Additionally, I made two more logo that depicts online shopping. Now, let me know your opinion on these designs.**
> 
> ![2](https://github.com/pooranjoyb/popShop/assets/119609866/9431559f-fd45-4324-98c9-09cc9d851f8e)
> ![3](https://github.com/pooranjoyb/popShop/assets/119609866/b02d3982-8561-4555-9f4f-f404a3170e99)
> 

@me-shweta I just want in the first image you add a bit of green color its more like pink and black only ...I really like the design though

**Comment by Mahitej28** [comment]
> okay @Mahitej28 ! 
> You want edits for this one .. right ?
> <img width="267" alt="Capture" src="https://github.com/pooranjoyb/popShop/assets/119609866/abbc0d36-4808-4670-b33b-36ea86c09d12">
> 

Yess edit in the sense color change design is nice

**Comment by me-shweta** [comment]
@Mahitej28 Which shade of green? Send me its code number, and let me know which color needs to be changed.

**Comment by Mahitej28** [comment]
> @Mahitej28 Which shade of green? Send me its code number, and let me know which color needs to be changed.

@me-shweta better share the figma file with me I will have a look

**Comment by me-shweta** [comment]
@Mahitej28 I made this on Canva ... so, send me your email and I will mail you the link.

**Comment by Mahitej28** [comment]
> @Mahitej28 I made this on Canva ... so, send me your email and I will mail you the link.

mahimachuri.28@gmail.com

**Comment by me-shweta** [comment]
done !

**Comment by Mahitej28** [comment]
> done !

@me-shweta we are good to go with the design for website logo !... you can create a pr for the same

**Comment by me-shweta** [comment]
@Mahitej28 that's the final one right ?
<img width="292" alt="sdfg" src="https://github.com/pooranjoyb/popShop/assets/119609866/1596ba7e-35bb-48e8-a93a-55115a63bd10">

**Comment by me-shweta** [comment]
@pooranjoyb Would you please tell me in which file you need the changes for the logo, or should I create a new branch for it?

**Comment by me-shweta** [comment]
I am currently submitting another pull request. Wait for some time. 
And @pooranjoyb  I have removed the dark yellow background and also @Mahitej28  what did you mean by routing the logo?

**Comment by pooranjoyb** [comment]
She meant that you need to set the `favicon` with the logo in the `index.html` file. 
Also make sure that you keep the `logo` with the filename `logo.ico` in `./public` directory.

@me-shweta

**Comment by me-shweta** [comment]
@pooranjoyb Is it correct now, or does it need more changes?
