### ISSUE TITLE
[BUG] : Navbar and Searchbar are not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [pooranjoyb/popShop#117]
### Description

The navbar is not responsive. The user profile logo is not appearing on small devices.
Also the search bar in explore products page is not completely visible.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/121669832/bf7f9cbb-224a-49d7-9783-e58715d7c97e)

### Any additional information?

Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @nagalakshmi08! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by AjayAsnani** [comment]
for now, this is pending because we have issues opened for the Logo and navbar once that is completed then only we will open an issue to make navbar responsive.

Till then you can look for something else @nagalakshmi08

**Comment by aMan404deep** [comment]
Hy !! I really want to work on this project . Please assign me this issue.

**Comment by pooranjoyb** [comment]
> Hy !! I really want to work on this project . Please assign me this issue.

go ahead 🚀 @aMan404deep

**Comment by pooranjoyb** [comment]
Update? @aMan404deep

**Comment by aMan404deep** [comment]
I am working on it !!

**Comment by aMan404deep** [comment]
I have made the changes . Kindly review them . One image is of smaller screen and the other is for large screen size .

![Screenshot 2024-06-01 181737](https://github.com/pooranjoyb/popShop/assets/121727857/ce24f620-c9bc-466c-971c-454b258cb341)
![Screenshot 2024-06-01 181804](https://github.com/pooranjoyb/popShop/assets/121727857/dd7506d9-02f5-4f6e-a288-fcea2251f71d)

**Comment by Mahitej28** [comment]
lgtm @aMan404deep go aheah, create a pr and take a pull from `dev`.

**Comment by Mahitej28** [comment]
@aMan404deep create a pr by EOD today, its really a small issue shouldn't take so much time.

**Comment by AjayAsnani** [comment]
Update @aMan404deep

**Comment by nagalakshmi08** [comment]
Hi, I want to fix this issue.

**Comment by pooranjoyb** [comment]
You can go ahead with this issue @nagalakshmi08 🚀
