### ISSUE TITLE
[Feature]: Workflow for closing old issues

### ISSUE THREAD

**Issue by Asymtode712** [pooranjoyb/popShop#118]
### Description

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@pooranjoyb please assign me this issue under gssoc'24

**Comment by pooranjoyb** [comment]
Well, this can't be worked upon right now ig. @Asymtode712 
Try with pinned issues! 
Happy coding :)
