### ISSUE TITLE
[Feature]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [pooranjoyb/popShop#120]
### Description

**As current workflow files only autocomments on issues created and PR raised**,

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Screenshots

![PR merged](https://github.com/pooranjoyb/popShop/assets/115717746/a6b090ce-2075-418c-a2a2-53c629197be7)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Asymtode712! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Asymtode712** [comment]
@pooranjoyb please assign me this issue under gssoc'24

**Comment by pooranjoyb** [comment]
Nice one, we can go ahead with this! @Asymtode712
