### ISSUE TITLE
[Feature]: Auto Commenting when an issue is closed by maintainer 

### ISSUE THREAD

**Issue by Asymtode712** [pooranjoyb/popShop#121]
### Description

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Screenshots

![issue closed](https://github.com/pooranjoyb/popShop/assets/115717746/41b75d53-7773-429f-b77f-a2659301e86f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Asymtode712! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Asymtode712** [comment]
@pooranjoyb please assign me this issue under gssoc'24

**Comment by pooranjoyb** [comment]
Not necessary! @Asymtode712
