### ISSUE TITLE
[Feature]: Want to do add-on more details on Product Deatil page.

### ISSUE THREAD

**Issue by Hardikchandra** [pooranjoyb/popShop#128]
### Description

Product Detail Page with;

1. Detail.
2. description.
3. delivery time.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Hardikchandra! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go ahead. Seems like a cool idea! @Hardikchandra

**Comment by harsh6045** [comment]
Hii @pooranjoyb 

The UI and mobile responsiveness of detail page is that interactive and user-friendly
Solution
** I Would like to complete Redesign the pages
** Make it User-Friendly and Interactive
** A good UI creates a good impression on the user

Additional context
kindly Assign me this issue under gssoc

**Comment by pooranjoyb** [comment]
> Hii @pooranjoyb 
> 
> The UI and mobile responsiveness of detail page is that interactive and user-friendly
> Solution
> ** I Would like to complete Redesign the pages
> ** Make it User-Friendly and Interactive
> ** A good UI creates a good impression on the user
> 
> Additional context
> kindly Assign me this issue under gssoc

Let's wait for @Hardikchandra 
If PR is not raised by 36hrs. U can work on it. @harsh6045

**Comment by harsh6045** [comment]
kindly Assign me this issue under gssoc

**Comment by pooranjoyb** [comment]
go ahead @harsh6045 🚀

**Comment by Mahitej28** [comment]
@harsh6045 Updates?

**Comment by Mahitej28** [comment]
@harsh6045 give updates by eod or will assign it to someone else.

**Comment by harini-1597** [comment]
Hi @Mahitej28 could I work on this issue?

**Comment by pooranjoyb** [comment]
One issue at a time :/ @harini-1597 Please finish up #200 and then you can work on this.

**Comment by Hardikchandra** [comment]
@pooranjoyb , can you assing me back this to me? Will surely create a PR in next 48 hrs.

**Comment by pooranjoyb** [comment]
Go ahead @Hardikchandra

**Comment by Mahitej28** [comment]
@Hardikchandra give updates by EOD

**Comment by pooranjoyb** [comment]
Closing as no updates. @Hardikchandra
