### ISSUE TITLE
[Style] : Responsive issue 

### ISSUE THREAD

**Issue by Sid-80** [pooranjoyb/popShop#13]
There is responsive issue at https://pop-shop-github.vercel.app/home/shop

<img width="242" alt="Screenshot 2024-05-11 104723" src="https://github.com/pooranjoyb/popShop/assets/101277141/0e96e274-7379-4e43-b37d-9c3afdf5ba19">

**Comment by Sid-80** [comment]
@pooranjoyb  Please assign me this issue under GSSOC24

**Comment by pooranjoyb** [comment]
Hii @Sid-80 you can start with the responsiveness of `Home`, `Shop`, `Cart`, `Product Details` and `Auth` page.
Finish up all the screen and make sure they are responsive :))) All the best!

Take the pull from `dev` branch and create the PR to `dev` branch. Happy Coding :)

**Comment by Sid-80** [comment]
Sure!

**Comment by Sid-80** [comment]
#20 I have created PR to dev branch. Please review it and let me know if any changes required!😊

**Comment by Sid-80** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/101277141/bfafb97b-ad19-431e-bb76-9cea17dde722)

Build not failed from my side?
