### ISSUE TITLE
[Feature] : photos corners alignment

### ISSUE THREAD

**Issue by gopalepic** [pooranjoyb/popShop#131]
### Description

If a little bit of rounded corners are applied along with some background color , then it would attractive and beautiful

I would like to contribute it under GSSOC 2024

### Screenshots

![Screenshot 2024-05-23 094856](https://github.com/pooranjoyb/popShop/assets/145182240/2fc8e06c-2b60-41c3-9970-d53293e5e7a8)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @gopalepic! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by gopalepic** [comment]
@pooranjoyb  pls add this enhancement label with GSSOC 2024 ,I Would like to contribute under GSSOC phase

**Comment by pooranjoyb** [comment]
> @pooranjoyb  pls add this enhancement label with GSSOC 2024 ,I Would like to contribute under GSSOC phase

Hello @gopalepic Ig this will change the overall theme.  Please go for other issues.
