### ISSUE TITLE
[DOCS] Small update in readme.md

### ISSUE THREAD

**Issue by Meetjain1** [pooranjoyb/popShop#132]
### Issue Description

Small update in readme.md file required currently our readme.md file is good but we can make it more attractive by replacing the static emojis with animated emojis in the file.

![popshop](https://github.com/pooranjoyb/popShop/assets/133582566/7aa42bb1-90ad-4a54-8c3e-42ed1822f774)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

@pooranjoyb assign this issue to me I will add it.

**Comment by pooranjoyb** [comment]
Congratulations, @Meetjain1! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Cannot be assigned as `gssoc` contributions :/
Look for some valid contributions :) 
Happy coding 👍🏼  @Meetjain1
