### ISSUE TITLE
Footer Navigation

### ISSUE THREAD

**Issue by Sid-80** [pooranjoyb/popShop#14]
## Description 
Navigation issue in footer section links of services

![image](https://github.com/pooranjoyb/popShop/assets/101277141/c81f5466-3c40-4403-9033-0b1b457f49e2)

**Comment by Sid-80** [comment]
@pooranjoyb  Please assign me this issue under GSSOC24.

**Comment by Srishtiii19** [comment]
@pooranjoyb assign this issue to me under Gssoc'24. I am a front-end dev, will contribute to your project with my full potential.

**Comment by pooranjoyb** [comment]
Go for it! @Srishtiii19

**Comment by Srishtiii19** [comment]
okay okay on it! thankyou! @pooranjoyb

**Comment by Mahitej28** [comment]
Completed
