### ISSUE TITLE
Needed to fix animation

### ISSUE THREAD

**Issue by AjayAsnani** [pooranjoyb/popShop#140]
### File Name

Home Page

### Reason for Refactoring the Code

The component takes more time to load and they are loaded when the screen is more than 50% empty.
this shouldn't happen They should load properly when the screen is not more than 50% empty.

https://github.com/pooranjoyb/popShop/assets/101942594/0d626edb-d54d-4399-b97f-47bba053e71f

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [ ] I am willing to work on this issue (optional).

**Comment by pooranjoyb** [comment]
Congratulations, @AjayAsnani! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Yogesh-ok55** [comment]
please assign this issue to me , i would like to work on it to fix animation problem

**Comment by AjayAsnani** [comment]
Ohk @Yogesh-ok55 go ahead.
