### ISSUE TITLE
[Feature] Sticky header

### ISSUE THREAD

**Issue by Che140401** [pooranjoyb/popShop#141]
### Description

For user interface we can do sticky header here which we are able to user can scroll and acccess heaader anywhere

https://github.com/pooranjoyb/popShop/assets/109230049/23a03b0d-5954-4f16-82a4-c7300abfd637

Not responsive stikcy header

https://github.com/pooranjoyb/popShop/assets/109230049/0fd1b02d-6381-41dc-8dc6-ed0197499604

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Che140401! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Closing this as `Navbar` is under construction :/
