### ISSUE TITLE
[Feature] Zoom products 

### ISSUE THREAD

**Issue by Che140401** [pooranjoyb/popShop#142]
### Description

Zooming products will increase user interface

Ex.

https://github.com/pooranjoyb/popShop/assets/109230049/4cd035b2-0eca-42ff-83c1-839e3b18a033

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Che140401! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Cool go ahead :) @Che140401 🚀

**Comment by Che140401** [comment]
when i run the npm run dev it is not running and getting blanked the screen


https://github.com/pooranjoyb/popShop/assets/109230049/fe6a4928-93ce-4a67-b90a-3d7a3aeaedd3

**Comment by pooranjoyb** [comment]
> when i run the npm run dev it is not running and getting blanked the screen
> Home.tsx.-.popShop.-.Visual.Studio.Code.2024-05-25.22-01-23.mp4

Please follow the `CONTRIBUTING GUIDELINES`

**Comment by pooranjoyb** [comment]
Closing as no updates!!!

**Comment by Che140401** [comment]
> Closing as no updates!!!

Hey can you please open issue again my device got dead
