### ISSUE TITLE
[Feature] `Enter` should also trigger `Login`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#149]
### Description

Currently we had to click on `Login` Button, we should also be able to Login after filling details and then `Enter Button`

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by yash28goyal** [comment]
I would like to contribute to this issue please assign this issue to me

**Comment by pooranjoyb** [comment]
Go ahead!
