### ISSUE TITLE
Adding a navbar

### ISSUE THREAD

**Issue by Monika-1082005** [pooranjoyb/popShop#15]
A navbar could be added which includes the sections as Home, New collections , Our Products and Footer(Consider this under Gssoc'24)

**Comment by pooranjoyb** [comment]
Hii @Monika-1082005 Go ahead with the issue. 
Raise a PR to `dev` and ensure that you maintain the theme and responsiveness!

**Comment by Monika-1082005** [comment]
> Hii @Monika-1082005 Go ahead with the issue. Raise a PR to `dev` and ensure that you maintain the theme and responsiveness!

Sure will keep that in mind! 👍🏻

**Comment by Vedant5751** [comment]
Assign it to me please

**Comment by pooranjoyb** [comment]
Finish this up by EOD please. @Monika-1082005

**Comment by Amitooo1** [comment]
Hey @pooranjoyb @Mahitej28, i would love to work on this issue, could you please assign this to me.

**Comment by pooranjoyb** [comment]
Go ahead 🚀 
Drop a PR by EOD. Also make sure to hide the `Navbar` in mobile devices, coz we already have the navigation in `avatar icon`

**Comment by Amitooo1** [comment]
Hey @pooranjoyb I'll raise a PR before morning

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb I'll raise a PR before morning

Use the `Navbar` used in the Link above, with framer-motion.

**Comment by Amitooo1** [comment]
Done with the UI and responsiveness part; need some more time to work on its proper functionality

**Comment by pooranjoyb** [comment]
> Done with the UI and responsiveness part; need some more time to work on its proper functionality

Karr lo bhai :) @Amitooo1

**Comment by Mahitej28** [comment]
@Amitooo1 updates? let us know the updates by EOD

**Comment by Amitooo1** [comment]
https://github.com/pooranjoyb/popShop/assets/108569153/d356f962-1fd2-44fa-a20d-e8daf116dc05

@Mahitej28 i came so far, but there are some UI glitches, may be due to high z-index values to some images. I am working on them 
and i appreciate your reviews on Navbar UI, as @pooranjoyb asked i added functionality of Navbar similar to the link above.

**Comment by pooranjoyb** [comment]
Hii @Amitooo1 I don't see it exactly the same tbh :/

Check this page. I don't need colors, I just need the exact same `Navbar`
Recheck https://play.coolpa.fun/

Use it @Amitooo1 

![image](https://github.com/pooranjoyb/popShop/assets/90945182/a4373d08-6167-456a-87f8-bbc7799fc168)

**Comment by Amitooo1** [comment]
Okay okay,
I assumed that you just need that behaviour,
Okay I'll add this now

**Comment by Mahitej28** [comment]
@Amitooo1 Update us till EOD today.
