### ISSUE TITLE
[Feature] Adding an eye button

### ISSUE THREAD

**Issue by ayushkamboj18** [pooranjoyb/popShop#151]
### Description

Adding an eye icon in the password field will be very helpful for the user to see the text written inside the password field on toggling the eye icon 
Describe the solution you'd like
The eye icon should be placed inside the password field on the signup page.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @ayushkamboj18! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by ayushkamboj18** [comment]
![330399892-c9b87834-5c16-4778-b1d4-be4e8a97e981](https://github.com/pooranjoyb/popShop/assets/114069208/0305adf1-c650-462d-b03c-23fa519bfb32)

**Comment by pooranjoyb** [comment]
Go ahead 🚀 @ayushkamboj18

**Comment by pooranjoyb** [comment]
Update? @ayushkamboj18
