### ISSUE TITLE
[Feature] Removing the static images and storing them in Supabase Storage

### ISSUE THREAD

**Issue by Yogesh-ok55** [pooranjoyb/popShop#152]
### Description

On home page the cart logo shows 8 cart element by default i think it is not as intended and on clicking add to cart it is not being added to cart and nor it have option to delete cart element 

### Screenshots

![Screenshot 2024-05-29 163225](https://github.com/pooranjoyb/popShop/assets/127961738/d514760d-85e1-4f10-8dc0-f173f65a29b2)
![Screenshot 2024-05-29 163425](https://github.com/pooranjoyb/popShop/assets/127961738/f968079b-62a9-4d48-b981-0eb71dd354ce)
![Screenshot 2024-05-29 163447](https://github.com/pooranjoyb/popShop/assets/127961738/2e21e193-4700-464d-a6f2-864089063174)

### Any additional information?

Please assign this issue under GSSOC'24 to me , i would like to work on this to solve this issue and want to add some extra functionality..

**Comment by pooranjoyb** [comment]
Congratulations, @Yogesh-ok55! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
How would you try to implement that? 
Coz we also need to store the cart items in Supabase @Yogesh-ok55

**Comment by Yogesh-ok55** [comment]
As you have stored images locally so for that I can use useContext() hook to implement this , for managing states or if you want I can also do this using Supabase but the problem here is that you have stored images locally..

**Comment by pooranjoyb** [comment]
I think we need to create a `Cart Slice` but yes keeping the images in Supabase Storage is also necessary. Can you work on that? @Yogesh-ok55

**Comment by Yogesh-ok55** [comment]
Yes I can do..

**Comment by pooranjoyb** [comment]
Okay drop me your email here in the comment. Store the images in supabase DB and use them in the frontend. 
We'll move to other tasks later. @Yogesh-ok55

**Comment by Yogesh-ok55** [comment]
yogeshh.ok@gmail.com

**Comment by pooranjoyb** [comment]
Invite sent for supabase. check your mail. @Yogesh-ok55

**Comment by pooranjoyb** [comment]
> Invite sent for supabase. check your mail. @Yogesh-ok55

![image](https://github.com/pooranjoyb/popShop/assets/90945182/ef0bcc35-a106-4fad-9019-ea3c66798eb8)

**Comment by Yogesh-ok55** [comment]
Received and joined

**Comment by pooranjoyb** [comment]
> Received and joined

All the best! @Yogesh-ok55

**Comment by Yogesh-ok55** [comment]
Sorry for being late , actually it was my end term going on , so I could not able to do this please assign again this to me I have already uploaded images to supabase and it is being rendered from supabase

**Comment by Yogesh-ok55** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/127961738/b349045f-effb-4799-9276-0ddcc1ed30a1)
showing this token is invalid..
so please do this again

**Comment by pooranjoyb** [comment]
it was expired as you were too late :) @Yogesh-ok55

**Comment by Mahitej28** [comment]
@Yogesh-ok55 what are the updates? give it by today eod

**Comment by Yogesh-ok55** [comment]
It is already done I have also create a PR but I have been asked to fix some build errors  which I have done but I don't what next to do

**Comment by Mahitej28** [comment]
@Yogesh-ok55 mention your issue number in the pr

**Comment by Yogesh-ok55** [comment]
> @Yogesh-ok55 mention your issue number in the pr

issue number #152 , PR number 220 , i have made some changes to fix build errors which was problem in my PR , these changes will solve build errors
