### ISSUE TITLE
[Feature] Enhance Authentication Screen

### ISSUE THREAD

**Issue by richab246** [pooranjoyb/popShop#156]
### Description

Improve the authentication screen by updating its design and functionality. This includes enhancing the user interface, making it more user-friendly, and ensuring it is responsive across all devices. The goal is to provide a smoother and more intuitive login and registration experience for users.

### Screenshots

![Screenshot 2024-05-30 194854](https://github.com/pooranjoyb/popShop/assets/79681567/174f5f1b-f46f-4d4e-a8cf-6ab6c0d4564b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @richab246! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Can you drop the figma/canva with the design that you're planning? @richab246

**Comment by richab246** [comment]
![Screenshot 2024-05-30 200556](https://github.com/pooranjoyb/popShop/assets/79681567/b2b321e9-7b36-4b0c-885d-46ab203bc3e0)


 Somewhat like this

**Comment by pooranjoyb** [comment]
I think the current one matches perfectly with the theme. You can just modify the current screen. @richab246

**Comment by richab246** [comment]
Okay, I will just enhance the current theme

**Comment by pooranjoyb** [comment]
Drop the design of canva/figma before working with the code.
@Mahitej28 will review it. @richab246

**Comment by Mahitej28** [comment]
@richab246 send the figma file by EOD.

**Comment by richab246** [comment]
![Screenshot 2024-06-01 161824](https://github.com/pooranjoyb/popShop/assets/79681567/fc9fb301-12f4-4215-b77c-8b04321124ac)

Figma link : https://www.figma.com/design/VlObI6CrzgfiAxWh66JOZd/Login-Page-(Community)-(Copy)?node-id=0-1&t=x7pAaFEqNfgn5Si5-1

**Comment by Mahitej28** [comment]
@richab246 just a suggestion always try to create frames rather then using rectangle and secondly the image resolution is getting distorted reduce the size give it a glass morphism effect. Give me edit access my email is mahimachuri.28@gmail.com

**Comment by richab246** [comment]
Sure! I will keep it in mind. I have given you editing access @Mahitej28

**Comment by Mahitej28** [comment]
@richab246 I have made the changes you can start working on implementing it.

**Comment by richab246** [comment]
I have created the pull request @Mahitej28, you can check now
