### ISSUE TITLE
Navigation Pages

### ISSUE THREAD

**Issue by lovelyANSH2410** [pooranjoyb/popShop#16]
Hey @pooranjoyb i have looked into the footer navigation options there are some pages missing i'll be creating some pages  also i will add navigations for those pages, I would request you to assign this task to me.

**Comment by pooranjoyb** [comment]
Hii @lovelyANSH2410 Can you describe the pages you wanna create. Coz I think most of the pages other than the Checkout page is already created. 

Looking forward to your thoughts :))
Happy Coding 🚀
