### ISSUE TITLE
[Feature] Add a proper add to cart system

### ISSUE THREAD

**Issue by masterboy376** [pooranjoyb/popShop#160]
### Description

A proper add to cart feature is missing. Nothing changes in cart when we click add to cart button. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @masterboy376! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
hello @pooranjoyb I  would like to solve this issue, I have past experience of implementing such features related to e com software. Also I have successfully setup the repo locally.

**Comment by pooranjoyb** [comment]
Duplicate #94 

Lmk if you wanna work on #94 @masterboy376
