### ISSUE TITLE
[Feature] Adding edit profile functionality.

### ISSUE THREAD

**Issue by yashi-15** [pooranjoyb/popShop#163]
### Description

Currently, the system stores default information such as first name, last name, address, phone number, gender, and account creation date.
I aim to implement a feature that automatically retrieves this data when a user signs up with their details. Additionally, users will have the ability to update certain information, such as their address and mobile number.

Kindly assign this issue to me, I want to work on this issue under GSSOC'24.

### Screenshots

![Screenshot (535)](https://github.com/pooranjoyb/popShop/assets/132138302/e4a0bdfa-a0fe-4785-ad87-c45ae2013967)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @yashi-15! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes, this is obviously the feature we need. We would need to implement is once #158 is done. @yashi-15

**Comment by pooranjoyb** [comment]
Just wait till tomorrow first half. @yashi-15

**Comment by pooranjoyb** [comment]
You can start working on this. Use a `Daisy UI` modal.
Also when user clicks on `Edit Profile` The model should popup and the old details should be passed to the input and user can edit them. That should be the workflow. @yashi-15

**Comment by yashi-15** [comment]
> You can start working on this. Use a `Daisy UI` modal. Also when user clicks on `Edit Profile` The model should popup and the old details should be passed to the input and user can edit them. That should be the workflow. @yashi-15

Sure @pooranjoyb

**Comment by yashi-15** [comment]
> You can start working on this. Use a `Daisy UI` modal. Also when user clicks on `Edit Profile` The model should popup and the old details should be passed to the input and user can edit them. That should be the workflow. @yashi-15

Hello @pooranjoyb, I have almost completed the work and would like to confirm with you .... which fields should be editable by the user. Currently, I have set the following fields as editable:

First Name - Editable
Last Name - Editable
Phone - Editable
Email - Not editable
Gender - Not editable
Account Creation Date - Not editable

**Comment by pooranjoyb** [comment]
Cool, we are good to go! 🚀 @yashi-15
