### ISSUE TITLE
[BUG] Explore products button not working.

### ISSUE THREAD

**Issue by yashi-15** [pooranjoyb/popShop#164]
### Description

On the profile page the "explore products" button is not working.

### Screenshots

![Screenshot (536)](https://github.com/pooranjoyb/popShop/assets/132138302/dab23676-9554-4daa-b366-f85b54a49300)

### Any additional information?

I can solve this issue, please assign it to me under GSSOC'24.

**Comment by pooranjoyb** [comment]
Congratulations, @yashi-15! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Fix it in #163 
Already added `level3` label with it. @yashi-15
