### ISSUE TITLE
Fix Navbar at top and close Dropdown on choosing an option

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#166]
### Description

The Navbar should be fixed at top so it will be usefull from anywhere in the website.
Also the dropdown menu should be closed automaticaly on choosing any option from it.

![image](https://github.com/pooranjoyb/popShop/assets/124615886/20768399-3cb0-4854-a12f-5de266a4cdcd)

I would love to contribute to this and make the user experience better.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I don't think fixed Navbar is necessary as of now. 
@AjayAsnani  Please do lmk if the second part of closing NavDropdown on click is necessary.

**Comment by Utsavladia** [comment]
should I fix the second part then ??

**Comment by AjayAsnani** [comment]
> I don't think fixed Navbar is necessary as of now. 
> @AjayAsnani  Please do lmk if the second part of closing NavDropdown on click is necessary.

Can be implemented as it's a good practice of selecting any option closes the NavDropdown

**Comment by pooranjoyb** [comment]
Ok go ahead 🚀 @Utsavladia
