### ISSUE TITLE
[BUG] Login with google is not working.

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#167]
### Description

Login in with google button is not working.
Add some backend to store the datas like firebase that will handle the singing with google also.

![image](https://github.com/pooranjoyb/popShop/assets/124615886/b479cba8-c802-4ff1-9779-7fe06c7143c0)

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Pending in #79 
closing as duplicate.
