### ISSUE TITLE
[BUG] add to cart is not functional

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#168]
### Description

should be some backend to store the data or may be on local system to store the cart item of user.

_No response_

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Work is in progress. We will tackle this soon. :/
