### ISSUE TITLE
[Feature] User should be allow to browse without login

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#169]
### Description

The user should be able to browse without login and while ordering it will ask for login that will enhance the user experience.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
What say @Mahitej28 @AjayAsnani ?
Do lmk your thoughts.

**Comment by Mahitej28** [comment]
> What say @Mahitej28 @AjayAsnani ? Do lmk your thoughts.

Well yes its a good idea, this way the user gets an idea about the stuff present on website it would improve user experience, looks good to me!

**Comment by AjayAsnani** [comment]
Yes this has to be implemented because if user have to login first before exploring the website can reduce traffic.

**Comment by Utsavladia** [comment]
So should I start working on it ??.. 
Also let me know if you have any special requirements or suggestion.

**Comment by AjayAsnani** [comment]
> So should I start working on it ??.. 
> Also let me know if you have any special requirements or suggestion.

What else you can add except this like you asked special requirements or suggestion.

**Comment by Utsavladia** [comment]
@AjayAsnani  
Asking for login when the user want to order.
Add to cart will store in local storage without login and transfer all after login but this can be implimented once the add to cart feature will be added.

**Comment by pooranjoyb** [comment]
Have a look on `ProtectedRoutes.tsx` possibly you'll need to change a lot there. @Utsavladia

**Comment by Mahitej28** [comment]
@Utsavladia update us by EOD

**Comment by Utsavladia** [comment]
@pooranjoyb
Sir,
I kept resolving the conflicts again and again but due to delay in merging the branch new conflicts used to come and now also I could have resolved it I dont know how this notification got missed.
sir I have spent time on this issue I request you to kindly let me fix and make it a successfull merge.

**Comment by pooranjoyb** [comment]
Mentors will check and reopen accordingly. @Utsavladia Check #195
