### ISSUE TITLE
 Clothes Size Options Not Functional

### ISSUE THREAD

**Issue by hithasam24** [pooranjoyb/popShop#17]
**Description:** When you try to click on the given size options : XL, L, M, S, there is no response.

**Expected Behavior:** Clicking on size options should trigger the selection process, allowing users to choose their preferred size effortlessly.
I am a GSSOC'24 contributor. Can you please assign this issue to me?  @pooranjoyb 
Please also mention GSSOC and level labels.
thank you.

**Comment by pooranjoyb** [comment]
Yes, make a selection element, and store the value selected in a state. Goog issue! Go for it :)) @hithasam24

**Comment by BHS-Harish** [comment]
Hey @pooranjoyb 

I'm interested to carry on the issue 

Please assign to me.

**Comment by pooranjoyb** [comment]
Go ahead! @BHS-Harish 🚀
