### ISSUE TITLE
[BUG] Add hover text to improve readability

### ISSUE THREAD

**Issue by AkhilaSunesh** [pooranjoyb/popShop#170]
### Description

![image](https://github.com/pooranjoyb/popShop/assets/140897461/55b61d61-08f8-41a6-81a9-ec845bf72b03)
Add hover text to the social media icons
Kindly assign this issue to me.

**Comment by pooranjoyb** [comment]
Congratulations, @AkhilaSunesh! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
You can add `Tooltip` to some of the important components.

Check this out and lemme know if you wanna continue. @AkhilaSunesh 

https://daisyui.com/components/tooltip/

**Comment by AkhilaSunesh** [comment]
Yeah, I please assign me. I will add them.

**Comment by pooranjoyb** [comment]
Okay, go ahead :)

Add Tooltip to 
- Navbar as Menu
- Social Icons with their respective names
- Filter button in Shop as filter

@AkhilaSunesh

**Comment by AjayAsnani** [comment]
What change can hover text bring in the context of user experience? @AkhilaSunesh

**Comment by pooranjoyb** [comment]
> What change can hover text bring in the context of user experience? @AkhilaSunesh

@AkhilaSunesh

**Comment by Mahitej28** [comment]
> Okay, go ahead :)
> 
> Add Tooltip to
> 
> * Navbar as Menu
> * Social Icons with their respective names
> * Filter button in Shop as filter
> 
> @AkhilaSunesh

@AkhilaSunesh have you started working on this?

**Comment by AkhilaSunesh** [comment]
> > What change can hover text bring in the context of user experience? @AkhilaSunesh
> 
> @AkhilaSunesh 

Hover text helps assure the user of the menu item they are currently viewing, making the overall browsing experience more satisfying.

**Comment by AkhilaSunesh** [comment]
> > Okay, go ahead :)
> > 
> > Add Tooltip to
> > 
> > * Navbar as Menu
> > * Social Icons with their respective names
> > * Filter button in Shop as filter
> > 
> > @AkhilaSunesh
> 
> @AkhilaSunesh have you started working on this?

Yeah, but I will have to halt the project as I have exams.

**Comment by pooranjoyb** [comment]
Okay then i guess we can work on this later. This is not at a priority list as of now.
