### ISSUE TITLE
[BUG] update price when we increase quantity in cart

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#171]
### Description

@pooranjoyb 

check this out,
when we increase the quantity the price should also be increased

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/d2d2973e-0c42-4fe3-9e0e-3d434b6bba1e)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @dhruv8433 The cart is completely static as of now. We have created `Cart Slice` in #162 
We are now planning to store Cart information in #109 
Hence we can proceed to this issue. 

We can keep a hold on this issue. @dhruv8433 
Looking for more valuable contributions :)

**Comment by pooranjoyb** [comment]
Hii @dhruv8433 wanna work on #109 ?

**Comment by dhruv8433** [comment]
Sure i would like to work on that

**Comment by pooranjoyb** [comment]
Go ahead with this then. @dhruv8433 🚀

**Comment by dhruv8433** [comment]
@pooranjoyb 

thank you :)

**Comment by dhruv8433** [comment]
@pooranjoyb 

i completed code for supabase 
i just need access of supabase dashboard so i can create `cart` table in that

**Comment by dhruv8433** [comment]
@pooranjoyb 

please assign me on #109

**Comment by dhruv8433** [comment]
@pooranjoyb 

ok

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb, I would like to work on this issue under Gssoc'24

Wait till #193 is merged. @masterboy376

**Comment by pooranjoyb** [comment]
@dhruv8433 You can continue this now if you want.

**Comment by dhruv8433** [comment]
@pooranjoyb 

please assign this to me so i can start work on this

**Comment by dhruv8433** [comment]
Thank you
