### ISSUE TITLE
[Feature] We can add BOOKMARK Section

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#172]
### Description

@pooranjoyb 

we can add bookmark section where use can store their favourite items

### Screenshots

we can add new `/bookmarks` route

![image](https://github.com/pooranjoyb/popShop/assets/114583978/4050472c-1f1c-44b9-8aaf-177604ae5959)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
We already have a `Add to Cart` Section :/ @dhruv8433
