### ISSUE TITLE
[Feature] Filter and Sort Dropdown Option on Shop Page

### ISSUE THREAD

**Issue by gdhyani** [pooranjoyb/popShop#173]
### Description

We can have an option to sort and filter products on the product page. This will ensure a better user experience and improve overall interaction with the website.

### Checklist

- [x] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @gdhyani! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Already exists!

![image](https://github.com/pooranjoyb/popShop/assets/90945182/38a2d0c8-b54e-4b01-8d6c-01201d3259b9)
