### ISSUE TITLE
[BUG] Not working Terms & Conditions, Privacy Policy and Cookies Links

### ISSUE THREAD

**Issue by gdhyani** [pooranjoyb/popShop#174]
### Description

Terms & Conditions, Privacy Policy, and Cookies Links are broken in the footer section. Such crucial information ought to be visible and available to users.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/67196176/55cd0e4f-47e4-4a4d-abf1-c131d980273e)

### Any additional information?

If you could provide me all the information, I could work on this.

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @gdhyani! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go ahead @gdhyani 🚀  
- Create a Single page that contains `Terms and Conditions` as well as `Privacy Policy`
- Remove Cookies.

**Comment by pooranjoyb** [comment]
1 PR should solves both #174 & #165. 
Read https://github.com/pooranjoyb/popShop/issues/165#issuecomment-2143991481

@gdhyani
