### ISSUE TITLE
[BUG] <profile page have bugs in showing firstname,lastname,phone number>

### ISSUE THREAD

**Issue by manikumarreddyu** [pooranjoyb/popShop#177]
### Description
first name,lastname ,phone number are not showing correctly after logged in

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/133508962/53bd1e8b-dd87-416e-8846-a4d137dddc1b)

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @manikumarreddyu! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by manikumarreddyu** [comment]
Please assign me this task under GSSOC'24 with level 3

**Comment by pooranjoyb** [comment]
Fixed Just Now. Was mentioned in #158
