### ISSUE TITLE
[BUG] <hover effect is not there while we are adding products to cart>

### ISSUE THREAD

**Issue by manikumarreddyu** [pooranjoyb/popShop#178]
### Description

mouse pointer is not changing while we are adding products to cart

### Screenshots

<img width="91" alt="image" src="https://github.com/pooranjoyb/popShop/assets/133508962/5da628db-8c31-4715-b612-8aa5ccd16a79">
![image](https://github.com/pooranjoyb/popShop/assets/133508962/16c76e6b-619a-4312-b041-02a5802c23e0)
<img width="942" alt="image" src="https://github.com/pooranjoyb/popShop/assets/133508962/808fbc39-952b-4932-865c-be75ec93ccb9">

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @manikumarreddyu! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by manikumarreddyu** [comment]
Please assign me this task under GSSOC'24

**Comment by AjayAsnani** [comment]
With this issue, you will just make changes to one line in CSS so what's needed to create an issue.
instead, you can open a bigger issue.
