### ISSUE TITLE
Fix some styling and spaces

### ISSUE THREAD

**Issue by AjayAsnani** [pooranjoyb/popShop#182]
### File Name

CSS

### Reason for Refactoring the Code

![Screenshot 2024-06-03 195156](https://github.com/pooranjoyb/popShop/assets/101942594/0e163692-0f0f-4cda-97e1-e78d27dd0a23)
There should not be too much space between components and make changes so text should be clearly visible on all devices.

![issue 2](https://github.com/pooranjoyb/popShop/assets/101942594/01dd11db-06d4-4b52-ab48-7742d3d79ad5)
Make this proper 

![issue5](https://github.com/pooranjoyb/popShop/assets/101942594/97c67f91-fd67-49f6-9c77-2050b82db777)
Content should be at the center.

![issue6](https://github.com/pooranjoyb/popShop/assets/101942594/ea5053fd-577f-4bfe-924a-646054cd3fd4)
Reduce the White Space between them and the Image should be on top (For mobile device only)

![issue7](https://github.com/pooranjoyb/popShop/assets/101942594/b17c3373-1385-4481-8b72-ce9a325387e3)
There should be space between the header and the component

![issue8](https://github.com/pooranjoyb/popShop/assets/101942594/953ca545-d8fa-48e5-858b-89983aeb2c36)
Add some more space

![issue4](https://github.com/pooranjoyb/popShop/assets/101942594/ecf5d041-c54e-4aae-a8ac-39168ea00533)
The image should be at the center.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [ ] I am willing to work on this issue (optional).

**Comment by pooranjoyb** [comment]
Congratulations, @AjayAsnani! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by BHS-Harish** [comment]
Hey @pooranjoyb 

Let me fix these errors.

Assign to me.

**Comment by Mahitej28** [comment]
Updates @BHS-Harish

**Comment by BHS-Harish** [comment]
Hello @Mahitej28 

I'm working and will complete by today.
