### ISSUE TITLE
[Feature] Improve the Buy Now Button 

### ISSUE THREAD

**Issue by SaiyamTuteja** [pooranjoyb/popShop#183]
### Description

Want to improve the buy now button as its normal but i can improve the style of it 
![image](https://github.com/pooranjoyb/popShop/assets/119167105/f53e45e2-1a15-4acc-9203-e44c29f51f49)

### My Design view
![image](https://github.com/pooranjoyb/popShop/assets/119167105/656b4756-5c41-42d1-a084-3ed10a74febb)

### After Hover
![image](https://github.com/pooranjoyb/popShop/assets/119167105/de1b1b86-bd61-49f4-b5cc-8aa4abdd385e)

It will improve the look and feel of the website 

Assign me this issue under **GSSOC2024**

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @SaiyamTuteja! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Sorry @SaiyamTuteja Really a minor change for a `gssoc` badge. We appreciate you to look for more valuable issues and try fixing them.
