### ISSUE TITLE
[BUG] Home Changed in responsive

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#185]
### Description

@pooranjoyb 

check this out,
due the fiilter option and search-bar it goes out of body in responsive

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/416a0a08-40af-468b-8ba7-2f165ce46bb4)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by AjayAsnani** [comment]
There's already an issue for this.
