### ISSUE TITLE
[Feature] Make a working contact form 

### ISSUE THREAD

**Issue by masterboy376** [pooranjoyb/popShop#187]
### Description

We need to enable users to send their queries, via email, to the admin using contact form. I would like to work on this issue under GSSOC'24. I would use emailJS to enable users to send their queries just by submitting the contact form.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @masterboy376! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb, I would like to work on this issue under GSSOC'24. I have past experiences of implementing such features. PTAL

**Comment by pooranjoyb** [comment]
Hii @masterboy376 how are you planning to proceed with this issue do let me know.

**Comment by AjayAsnani** [comment]
instead, we can also add a FAQ section? @masterboy376

**Comment by masterboy376** [comment]
Hello @pooranjoyb, I plan to use EmailJS sdk, a js based smtp service, to solve this issue.
I will collect the fields from contact form and then send this user query to admin's email using sendTo() function.
I hope to create a PR for this within few hours of issue assignment.

**Comment by masterboy376** [comment]
Hello @AjayAsnani, This sounds good
Since I have some prior experiences of creating such systems, I believe to fix the issue soon. After this we can defiantly add a FQA section.

**Comment by AjayAsnani** [comment]
Give us some time we are discussing this what to do exactly

**Comment by pooranjoyb** [comment]
Hey @masterboy376 we decided to keep both, the FAQ as well as the Contact. So in ContactUs page, you can create a section above the form with basic FAQs related to eCommerce. And you can write something that, for furter info you can contact us through the form.

**Comment by pooranjoyb** [comment]
Do the SMTP functionality too :) @masterboy376
