### ISSUE TITLE
[Feature] Refactor `Terms&Conditions` UI

### ISSUE THREAD

**Issue by masterboy376** [pooranjoyb/popShop#188]
### Description

- Use the `Head` component for the titles. Update all the headings in this page. 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/2b9d5e31-5e25-4742-bfa0-492251ba0a2c)

- There should be only these titles. (Terms and Conditions, Cookies, License). Rest remove all.
- Now beautify these three. Use lists and underline and images if needed.
- Maintain the theme and colors of the website if you're using any.
- Remove unnecessary links like `home/terms-and-conditions#terms` and update the `Footer.tsx` accordingly.
- There should be only one link i.e `Terms and Conditions` in the Footer. That'll do.
- Make sure it is _**mobile responsive**_.

Do ask @Mahitej28 or @AjayAsnani for nay doubts. They'll help you. @yashi-15

**Comment by pooranjoyb** [comment]
Congratulations, @masterboy376! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb, I would like to work on this issue under GSSOC'24. I have past experiences of implementing such features. PTAL

**Comment by pooranjoyb** [comment]
One issue at a time @masterboy376

**Comment by yashi-15** [comment]
I can work on this isuue.. Kindly assign it to me under GSSOC'24.

**Comment by pooranjoyb** [comment]
Hii @yashi-15 seen your work in the last PR. Just wanted to modify this issue for the refactoring of `Terms and Conditions` UI. Would you like to work on that?

**Comment by pooranjoyb** [comment]
Okay I am changing the issue title and description. Please do the changes accordingly. @yashi-15

**Comment by AjayAsnani** [comment]
Double-check the responsiveness on every breakpoint. @yashi-15

**Comment by Mahitej28** [comment]
Hey @yashi-15 give your updates by eod, also do let me or @AjayAsnani know incase of any doubts.

**Comment by yashi-15** [comment]
Hey @Mahitej28 @AjayAsnani , I have done some changes till now, 

Changes done:
- Removed headings other than Terms and Conditions, Cookies, License.
- Added images for each head.
- Added list, bold, justify text properties to the text content and head styling to headings.

Changes yet to be made:
- Check responsiveness
- Changes in footer and link.
- Checking responsiveness

I want to confirm from your side if the images are looking good or not (especially `Cookies` one, for which I am doubtful). Should I remove all the images or change any. Please give me your suggestions...

![Screenshot (576)](https://github.com/pooranjoyb/popShop/assets/132138302/a2128eb4-44cf-48a4-bfd3-7e794696d08f)
![Screenshot (577)](https://github.com/pooranjoyb/popShop/assets/132138302/779fafd6-aa64-416c-9120-fe47b56cde57)
![Screenshot (578)](https://github.com/pooranjoyb/popShop/assets/132138302/12912562-d7c4-4884-b965-9c88bdba9cf0)

**Comment by pooranjoyb** [comment]
Looks good to me! @Mahitej28 Please have a look and suggest the changes if necessary.

**Comment by AjayAsnani** [comment]
Ohk images are looking fine.

**Comment by pooranjoyb** [comment]
We can go ahead for a PR then @yashi-15 
@AjayAsnani or @Mahitej28 will review and merge it.

**Comment by AjayAsnani** [comment]
Yes first complete all the mentioned issues and make a PR @yashi-15

**Comment by yashi-15** [comment]
Sure! @pooranjoyb @AjayAsnani
