### ISSUE TITLE
[BUG] alignment needs to be done between search bar and apply filters

### ISSUE THREAD

**Issue by kapilG0** [pooranjoyb/popShop#189]
### Screenshots

![Screenshot_20240604_165801](https://github.com/pooranjoyb/popShop/assets/59639410/10fb5689-2792-48a2-be62-a2339c8efc4e)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @kapilG0! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by kapilG0** [comment]
Hello @pooranjoyb please assign this issue to me under gssoc 24

**Comment by pooranjoyb** [comment]
Hii @kapilG0 you can check for issues that are not created. Please have a look on recent `Preview Deployment`
Closing as duplicate in #185
