### ISSUE TITLE
Adding a styling feature where one can style and select clothing's by combining

### ISSUE THREAD

**Issue by Chelseasingla1** [pooranjoyb/popShop#19]
I would like to add a feature where one can combine different clothing's and style it by their perspectives.
Or maybe i can try to add feature where one can get recommendations to buy item with another item to make it appealing and more selling. Please assign me this issue under GSSoC'24

**Comment by Mahitej28** [comment]
@Chelseasingla1 you can work on this issue now, also try to complete it in stipulated time period

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 you can work on this issue now, also try to complete it in stipulated period. Take the pull from dev branch and create the PR to dev branch. Best of luck!

Okay Thankyou!!
