### ISSUE TITLE
[BUG] <add to cart then update the cart badge value>

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#190]
### Description

when user add to cart then increase the value on cart badge on navigation 

here always display 0 value ,increase value when user add the cart

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/137641079/e4b4814b-c169-4d7e-958a-e74c2eca0abf)
![image](https://github.com/pooranjoyb/popShop/assets/137641079/31adcaae-d895-4d7e-a476-aa2a414b73ae)

### Any additional information?

here issue is i click on add to cart then that item add to cart sucess toast show but not in display in cart badge 

### What browser are you seeing the problem on?

Firefox

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @Varsani2520 This issue already exists in #109 
Please look for more issues in the app and raise issues accordingly. 
Closing this as duplicate. Happy coding :)
