### ISSUE TITLE
[UI] Checkout Page UI

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#191]
### Create a Checkout Page that will have the following.

- Billing Details is not required coz we already have that in cart.
- Just the payment option is good. Rest everything remains same.
- Make sure it is mobile responsive.

### Screenshot

![image](https://github.com/pooranjoyb/popShop/assets/90945182/2f5bc8b6-19e6-4a91-8cb3-d8d5d06264dd)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by BHS-Harish** [comment]
Hey @pooranjoyb 

I would like to working on the issue.

Please assign it to me.

**Comment by pooranjoyb** [comment]
Go ahead 🚀 @BHS-Harish

**Comment by Mahitej28** [comment]
@BHS-Harish give us updates by EOD today.

**Comment by BHS-Harish** [comment]
Hello @Mahitej28 

I'm working on the issue 
I will complete within tomorrow.
