### ISSUE TITLE
[BUG] Buy Now button not working 

### ISSUE THREAD

**Issue by namandude** [pooranjoyb/popShop#197]
### Description

Hey !!
I faced the issue, if i click on item it get added but on buy now button that isnt working , item not even adding in the bucket.
Please assign this me under Gssoc so that i can start working on it immediately.
Thank You!!

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/118013565/4b547d07-0cd7-47ba-b933-f482e12382fd)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @namandude! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Future plan. Currently we're working on other functionalities. @namandude
