### ISSUE TITLE
[BUG] Cart count isnt working

### ISSUE THREAD

**Issue by namandude** [pooranjoyb/popShop#198]
### Description

Hey !!
There is the problem the counting of the number of the item isnt working even on added it shows 0 .
Which is the huge bug here . 
I wish to resolve this down , please assign me this under Gssoc , so that i can immediately start working on this.

### Screenshots

![Screenshot 2024-06-05 233844](https://github.com/pooranjoyb/popShop/assets/118013565/37d8134a-c45c-408f-8527-49dbb99d96e9)

### Any additional information?

This is the huge bug which need to be fixed asap. 
Please assign this to me,

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @namandude! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
As of now we are working on the cart #109
