### ISSUE TITLE
[Bug] The submenu in profile section

### ISSUE THREAD

**Issue by Disha-Hati** [pooranjoyb/popShop#2]
![image](https://github.com/pooranjoyb/popShop/assets/70029959/81c2d4f8-a69e-4f7a-be01-ac5ecba3215f)
 It should show Logout when it's logged in 
 
 Can you please assign this to me?

**Comment by pooranjoyb** [comment]
Will have to setup Redux for state management for thr project. This hasn't been done yet. I'll let you know by tomorrow.

**Comment by Disha-Hati** [comment]
Ok Sure. Thank you.
