### ISSUE TITLE
[BUG] UI breaks in zoomed-out

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#200]
### Description

Fix this spacing issue.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/fd27202a-77bb-4637-bb6a-3fedd31e8413)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by harini-1597** [comment]
HI! I am willing to work on this issue!

**Comment by pooranjoyb** [comment]
Go ahead! 🚀 @harini-1597

**Comment by harini-1597** [comment]
I'm assuming you'd like to fix this container right? As currently it is not displayed fully when viewed on a computer screen

https://github.com/pooranjoyb/popShop/assets/128628820/4530e21b-315a-463b-8873-6f79c8c7fa34

**Comment by pooranjoyb** [comment]
> I'm assuming you'd like to fix this container right? As currently it is not displayed fully when viewed on a computer screen
> Recording.2024-06-07.002645.mp4

Yes, this is exactly we  need to fix, possibly a simple css fix will do.

**Comment by Mahitej28** [comment]
@harini-1597 updates?

**Comment by harini-1597** [comment]
yeah, how's this?

https://github.com/pooranjoyb/popShop/assets/128628820/e4f1e080-3e9f-481b-8295-a7ca92a5eab4

**Comment by harini-1597** [comment]
how's this?

https://github.com/pooranjoyb/popShop/assets/128628820/28d90ff8-1510-4e44-a60b-83429c4cb55b

**Comment by pooranjoyb** [comment]
> how's this?

Awesome, raise a PR, either me, @Mahitej28 or @AjayAsnani will merge it. 
@harini-1597

**Comment by Mahitej28** [comment]
> how's this?
> 
>  Recording.2024-06-07.174311.mp4

Looks good to me too, raise a pr by EOD @harini-1597
