### ISSUE TITLE
[BUG] Fix centering issue in Product Details page

### ISSUE THREAD

**Issue by harini-1597** [pooranjoyb/popShop#202]
### Description

currently the Quantity container in the product details page is not centered.
![Screenshot 2024-06-06 175307](https://github.com/pooranjoyb/popShop/assets/128628820/cba3186b-0a2b-4a8b-b1e6-a5dc767e6c30)

I'll fix this

**Comment by pooranjoyb** [comment]
Congratulations, @harini-1597! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Will be fixed in another issue. A really small issue to be assigned as `gssoc`.
