### ISSUE TITLE
[DOCS] Improve README.md by adding Tech Stack icon banners

### ISSUE THREAD

**Issue by harini-1597** [pooranjoyb/popShop#203]
### Issue Description

The header section of the Readme should offer an attractive summary of the project, which includes a logo, the project github stats and tech stack used. 
Currently, the tech stack is listed in a list format which makes it look very mid.
Also, there are way too many github stats to look at.

### Screenshots or Examples (if applicable)

![Screenshot 2024-06-06 175956](https://github.com/pooranjoyb/popShop/assets/128628820/aafed361-c008-4300-9736-8ff9b4c568f0)

### Proposed Solution (optional)

I will make the README look as above, minimal but attractive.

_Do assign it to me under the gssoc label_

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @harini-1597! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Shubham-Zone** [comment]
@pooranjoyb please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by Mahitej28** [comment]
Go ahead @harini-1597 complete it within two days or I will close it

**Comment by harini-1597** [comment]
https://github.com/pooranjoyb/popShop/assets/128628820/016b2bbf-3e1e-4bee-ad80-5547434f0998

hope it looks good

**Comment by AjayAsnani** [comment]
yes this is good @harini-1597

**Comment by Mahitej28** [comment]
@harini-1597 lgtm create a pr by EOD today.
