### ISSUE TITLE
[BUG] Re-designing Navbar

### ISSUE THREAD

**Issue by Ridhima10** [pooranjoyb/popShop#204]
### Description

The styling of navbar is not matching with the color theme of the website

### Screenshots

![Screenshot 2024-06-07 102704](https://github.com/pooranjoyb/popShop/assets/85826117/ad20f72f-5ef5-4205-a20e-df9872af12d8)

### Any additional information?

I would like to re-design it to make it more appealing and make it match with the color theme of website
I will also add animation or hover effect

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @Ridhima10! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Shubham-Zone** [comment]
@pooranjoyb please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
