### ISSUE TITLE
[BUG] Misalignment of heading "Product detail"

### ISSUE THREAD

**Issue by Ridhima10** [pooranjoyb/popShop#205]
### Description
Issue 1-
The heading is not aligned like other headings

### Screenshots

![Screenshot 2024-06-07 103003](https://github.com/pooranjoyb/popShop/assets/85826117/2e07e1a3-cfa3-497a-bb06-b402934eed33)

### Any additional information?

I will align it to center

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

Issue 2-
Fashion is not visible
![Screenshot 2024-06-07 103419](https://github.com/pooranjoyb/popShop/assets/85826117/ee573423-08bd-4463-9d4f-33e986847cc0)

Issue 3-
Re-designing Navbar for better UI and UX
![Screenshot 2024-06-07 102704](https://github.com/pooranjoyb/popShop/assets/85826117/f1545926-9757-4ebc-89d8-6397e9742dff)

**Comment by pooranjoyb** [comment]
Congratulations, @Ridhima10! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Shubham-Zone** [comment]
@pooranjoyb please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by Mahitej28** [comment]
@Ridhima10 I have seen you have created 3 different issues for 3 different things which are not even major, I suggest you to put everything u need to work upon at a single place, mention all your issues here.

**Comment by AjayAsnani** [comment]
Also, there are more changes to make components responsive will mention it here if you want to work on them. @Ridhima10

**Comment by Ridhima10** [comment]
@AjayAsnani  yeah sure. I am open to work

**Comment by Ridhima10** [comment]
@Mahitej28 Okay. I will do that

**Comment by Ridhima10** [comment]
@Mahitej28 Kindly review the updated issue please

**Comment by Mahitej28** [comment]
> Also, there are more changes to make components responsive will mention it here if you want to work on them. @Ridhima10

@AjayAsnani will mention the changes need to be made, @Ridhima10 you work upon that

**Comment by Ridhima10** [comment]
@Mahitej28 @AjayAsnani okay

**Comment by AjayAsnani** [comment]
![7](https://github.com/pooranjoyb/popShop/assets/101942594/6be8770d-4383-4561-9316-e6b3369c6317)
![6](https://github.com/pooranjoyb/popShop/assets/101942594/24270c1f-048d-48f9-8695-b6a5c5fda52a)
![5](https://github.com/pooranjoyb/popShop/assets/101942594/1ceec9bf-e633-4050-9772-f9e6f0460916)
![4](https://github.com/pooranjoyb/popShop/assets/101942594/dd120eb7-4d21-46e4-8497-212ff6281a51)
![3](https://github.com/pooranjoyb/popShop/assets/101942594/14695295-ae67-456b-a87a-a6efe6cb6130)
![2](https://github.com/pooranjoyb/popShop/assets/101942594/84858f64-3852-4941-ade2-e7246269db84)
![1](https://github.com/pooranjoyb/popShop/assets/101942594/888c996a-57cb-4191-b95a-0f34f7a7c65b)


There are some issues with responsiveness.
images should be at center, and Spacing between components is not proper. @Ridhima10

**Comment by pooranjoyb** [comment]
work on the changes mentioned @Ridhima10

**Comment by Ridhima10** [comment]
@pooranjoyb okay sure

**Comment by Mahitej28** [comment]
@Ridhima10 any updates? do let us know if anywhere you need help!

**Comment by Ridhima10** [comment]
@Mahitej28 There is an electricity issue in my area due to which it will take some time but i'll try to do it as soon as possible
