### ISSUE TITLE
[BUG] Heading is not visible

### ISSUE THREAD

**Issue by Ridhima10** [pooranjoyb/popShop#206]
### Description

The "Fashion" keyword in "Eat, Sleep, Fashion, Repeat" is not visible

### Screenshots

![Screenshot 2024-06-07 103419](https://github.com/pooranjoyb/popShop/assets/85826117/03875598-e1bf-4bb2-b292-1f875773de28)

### Any additional information?

N/A

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @Ridhima10! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Shubham-Zone** [comment]
@pooranjoyb please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by Mahitej28** [comment]
@Ridhima10 thanks for pointing it out, but it is really a small issue to work upon, kindly look for any other issue :)
