### ISSUE TITLE
Updating and Enhancing the Contributions.md file

### ISSUE THREAD

**Issue by pranavc13** [pooranjoyb/popShop#207]
### Issue Description

I am interested in contributing to the project by editing the Contribution.md file by adding new guidelines and process such as:

Providing links for learning basics of Github
Pull Request process;
Community Guidelines
Code Reviews
Spreading a word about the project  etc

By providing clear and comprehensive guidance, we can encourage more contributors to participate in the project.
Our contributions.md file could me made more attractive and bring the interest of different people.

Could you please assign me the project under GSSOC'24?

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pranavc13! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@pranavc13 as of now we don't think to change our contribution guidelines, kindly find any other issue to work upon.. :)
