### ISSUE TITLE
improving drop down menu

### ISSUE THREAD

**Issue by mahek0620** [pooranjoyb/popShop#210]
### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/136893675/cfde8e15-9e2e-4e52-a120-96bc4c4e9ca7)

**Comment by pooranjoyb** [comment]
Congratulations, @mahek0620! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Please show us the design or the improvement you're planning. @AjayAsnani or @Mahitej28 will review and assign accordingly. :) @mahek0620

**Comment by AjayAsnani** [comment]
The Dropdown is fine what changes you want to bring in that? @mahek0620

**Comment by Mahitej28** [comment]
We don't need any improvement for drop-down menu as of now, kindly work on any other issue :)
