### ISSUE TITLE
[Mode] <Dark /Default Mode toggler>

### ISSUE THREAD

**Issue by Vipullakum007** [pooranjoyb/popShop#213]
### Description

This good website needs Dark / Default Toggler that make it more interesting

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Vipullakum007! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Vipullakum007** [comment]
hey @pooranjoyb  , please assign i want to work on it.

**Comment by pooranjoyb** [comment]
Hii @Vipullakum007 We plan to do this in July. :)
