### ISSUE TITLE
[Section] <add Trending section under Collection>

### ISSUE THREAD

**Issue by Vipullakum007** [pooranjoyb/popShop#214]
### Description

we can add Trending section under Collection that is using keep tracks of monthly most selled items take it into trending section top 4 -5 items.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Vipullakum007! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Vipullakum007** [comment]
hey @pooranjoyb , please assign to me i want to work on it.

**Comment by pooranjoyb** [comment]
Well, awesome idea. but as of now we plan to implement the basic functionalities of the eCommerce first. :)
We'll keep this for july. @Vipullakum007
