### ISSUE TITLE
[Feat] : we can fetch cart from supabase

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#215]
### Description

@pooranjoyb 

We can fetch cart items from supabase 
And display in cart page

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go for it! @dhruv8433 🚀

**Comment by dhruv8433** [comment]
Thank you
