### ISSUE TITLE
[Feature]  Creating a subscribe mail section in the landing page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [pooranjoyb/popShop#217]
### Description

 Creating a subscribe mail section in the landing page

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/125277258/375ef7ab-aa5f-4c76-8c47-02c66375d768)
here we can implement that

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @RamakrushnaBiswal! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by AjayAsnani** [comment]
Go ahead @RamakrushnaBiswal

**Comment by Mahitej28** [comment]
@RamakrushnaBiswal update us by eod
