### ISSUE TITLE
[Feature] Add a Light/Dark Mode feature

### ISSUE THREAD

**Issue by Shivam250702** [pooranjoyb/popShop#221]
### Description

I want to add a light/dark mode feature in this project. Will apply it on left side of the cart button

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/103785990/0d6aaa6b-c1c8-45e2-9d1a-614b94f7dd18)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Shivam250702! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well, we'll do it in July! @Shivam250702
