### ISSUE TITLE
[Feature] Remove item from cart as well supabase

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#222]
### Description

@pooranjoyb 

we can add remove icon in cart and when user click on that 
item should be removed from redux as well supabase 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/b2f33971-d7af-4f79-b214-0c41138b0d05)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
Thank you
