### ISSUE TITLE
[Feature] When we increase quantity the price must be increased

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#224]
### Description

@pooranjoyb 

in cart section, when we increase the quantity of product the price must be increased 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/94309d42-8706-4b9e-a498-e8b3f23e4ff7)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>
