### ISSUE TITLE
[Feature] Update `Order Summary` w.r.t cart items.

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#227]
### Tasks
- Fetch items from the user's cart and render it in `Checkouts Order Summary`.
- Calculate and show the total bill.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/084af47d-8a0d-4785-b08c-9a7dfcbff2e1)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this

**Comment by pooranjoyb** [comment]
Finish up #228. One issue at a time. :/

**Comment by dhruv8433** [comment]
@pooranjoyb 

completed please check pr and assign this to me

**Comment by pooranjoyb** [comment]
Go for it 🚀

**Comment by dhruv8433** [comment]
Thank you :)
