### ISSUE TITLE
[Feature] : Add toast message when removing items from cart

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#228]
### Description

@pooranjoyb 

we can display toast message when remove item from cart

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/3fea857a-6cca-4057-86f5-a269b94f92be)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Easy peasy! shouldn't take more than 10 mins! XD @dhruv8433

**Comment by dhruv8433** [comment]
yes i completing now...
