### ISSUE TITLE
[Enhancement] : Add Proper Meta Tags, Description, and Missing Icon

### ISSUE THREAD

**Issue by mahekkg** [pooranjoyb/popShop#23]
Hello @pooranjoyb and @Mahitej28 

I've conducted a review of website and identified areas where we can improve its search engine optimization (SEO) on a basic level. As someone experienced in contributing to open-source projects, I'm confident in addressing these aspects effectively.
Let's work together to enhance the SEO performance of our website for better user engagement and brand representation by adding favicon titles , description.

Looking forward to your input and collaboration!
Please assign me this under GSSOC'24

**Comment by Mahitej28** [comment]
Hello @mahekkg can you elaborate exactly what all things you will work upon.

**Comment by mahekkg** [comment]
Hello @Mahitej28 

Favicon: I'll ensure that the website has a favicon, which is a small icon displayed in the browser tab. This helps in brand recognition and improves the overall user experience.
![image](https://github.com/pooranjoyb/popShop/assets/85817366/97fa4034-f660-4457-b8b2-89ef493b3c51)



Titles: I'll review and optimize the titles of web pages to include relevant keywords. Titles are important for both search engines and users as they give an idea of what the page is about.

Descriptions: I'll craft compelling meta descriptions for each page.  A well-written meta description can entice users to click on the link, thus increasing organic traffic.

**Comment by pooranjoyb** [comment]
Update? @mahekkg

**Comment by mahekkg** [comment]
@Mahitej28 Please assign the issue so I can start working.

**Comment by pooranjoyb** [comment]
@mahekkg If you do plan to create the Logo for the App, drop it here in comments, me & @Mahitej28 will review the changes. All the best! :rocket:

**Comment by mahekkg** [comment]
Tried something minimal according to the website (background color is only for clear view)
Open to suggestions.

![image](https://github.com/pooranjoyb/popShop/assets/85817366/fcc5a689-99b1-4ba6-acda-a825954f2844)

**Comment by pooranjoyb** [comment]
Hey @mahekkg 

Use these color theme : 
- `#06D6A0`
- `#EF476F`
- `#FFD166`
- `#118AB2`
- `#073B4C`

**Comment by mahekkg** [comment]
Hey @pooranjoyb 
Can you provide only one colour which you want? As favicon will be only one and in the previous fav icon I have used #EF476F

**Comment by pooranjoyb** [comment]
keep it `#06D6A0` and remove the bg color. @mahekkg

**Comment by mahekkg** [comment]
Yeah sure will make the required changes 
Okay the background colour is only for reference.

**Comment by Mahitej28** [comment]
@mahekkg any updates?

**Comment by mahekkg** [comment]
Yes will mostly be done by tomorrow EOD , facing some favicon issues.
