### ISSUE TITLE
[Feature] Initiate a `Storage Bucket` in Supabase for `Store` items

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#232]
### Description

As of now we are rendering static images from `public/assets` but eventually we can't keep store items in `src`.
Hence we plan to initiate `Storage Bucket` to store the images of products in the supabase itself. 

#### Tasks : 
- Initiate storage bucket for the application in supabase.
- Store all the Store images there. 
- Map them accordingly in the `Store`
- Functionalities like `Add to Cart`, `Remove from Cart`, etc should work perfectly.

For further information checkout 
- [Supabase-Storage](https://supabase.com/docs/guides/storage)
- [Storage-Buckets](https://supabase.com/docs/guides/storage/buckets/fundamentals)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb I have no issue assigned to me right now. I would like to work on this issue under gssoc'24

**Comment by pooranjoyb** [comment]
Go Ahead. Drop a PR by Tomorrow EOD. @masterboy376

**Comment by masterboy376** [comment]
@pooranjoyb , for this issue should I create a bucket solely for storing cart images, with name such as "cart_images_bucket"

**Comment by pooranjoyb** [comment]
yes make it `store-bucket`

**Comment by masterboy376** [comment]
Ah, acctually I created the PR and the bucket with images_bucket

**Comment by pooranjoyb** [comment]
> @pooranjoyb Ah, actually I created the PR and the bucket with images_bucket. Just a suggestion, wouldn't it be more comprehensive to name it images_bucket if we are just storing the images in it.

Works!
