### ISSUE TITLE
[Feature] Make Payment option functionals

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#233]
### Description

@pooranjoyb 

we can make this payment option functionals
we can add stripe payment gateway to take card info and make payment in `test` mode

### Screenshots

something like this

![image](https://github.com/pooranjoyb/popShop/assets/114583978/38f2ec1b-fac5-448c-95bf-6abddca4b96d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Thoughts on this? @Mahitej28 @AjayAsnani

**Comment by pooranjoyb** [comment]
Okay so after the payment is done. Save it to the order's table (create one) keep the necessary fields in the table. Coz we'll have the Orders page coming up soon. Check #234 for reference and create the fields accordingly in supabase table.

Use a modal (Daisy UI) to notify user that Order has been placed successfully with the order_id (some hash)

Take a fresh pull from dev before working on this. @dhruv8433

**Comment by dhruv8433** [comment]
ok thank you @pooranjoyb
