### ISSUE TITLE
[UI] My Orders Page

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#234]
### Description

Use this template idea to create the `My Orders` page. 

- My Orders should be in `Profile Icon` in `Navbar`
- Create a separate route `/home/my-orders`
- Use Daisy-UI components for the table. 
- You can use static-data as of now. untill we integrate real-data from database.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/98edb030-64bd-4466-9ab6-055211a4af54)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Asymtode712** [comment]
@pooranjoyb I would like to work on this issue, please assign me

**Comment by Asymtode712** [comment]
Hey @pooranjoyb,

This is the current status of UI for `My Orders` any changes or suggestions

![Current status](https://github.com/pooranjoyb/popShop/assets/115717746/8828b05f-e5d5-434b-90be-bef11a3d97b9)

**Comment by pooranjoyb** [comment]
Awesome @Asymtode712 just name the header of View as Action and make it a mygreen button.

**Comment by Asymtode712** [comment]
Sure, after doing the changes I will raise a PR, you can then review and suggest me changes accordingly if there are any
