### ISSUE TITLE
[BUG] Fix the searchbar in `Store`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#237]
### Task : 

The search should list the item in real-time.

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this issue
please assign me

**Comment by pooranjoyb** [comment]
Yes, go ahead! 🚀

**Comment by dhruv8433** [comment]
Thank you @pooranjoyb

**Comment by pooranjoyb** [comment]
you can go ahead with this one i guess. @dhruv8433

**Comment by dhruv8433** [comment]
Yaa sure
