### ISSUE TITLE
[BUG] Profile Details are not updating onChange 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#238]
### Description

This is the message when we try to update the UserData

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/a1425458-a8dc-4ca0-8293-59a37c6cd063)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
hello @pooranjoyb,
I am open to work on this issue under gssoc'24.

**Comment by pooranjoyb** [comment]
go ahead :) @masterboy376

**Comment by masterboy376** [comment]
Hi @pooranjoyb, I think I have to verify primary key and various fields in the supabase table.
So kindly provide me the access to the supabase project.
email: masterboy376@gmail.com
