### ISSUE TITLE
[Feature] Design `Address` Form before checkout

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#240]
### Description

@pooranjoyb 

we can add one beautiful address taking form
when user try to checkout their cart,
first we take user's address and save it maybe in `redux` or `localstorge`

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/6b2c305c-4183-4fea-9065-bf024268c5de)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Keep this as pending. We'll do it later. :/

**Comment by pooranjoyb** [comment]
Thoughts on this @Mahitej28 @AjayAsnani

**Comment by Mahitej28** [comment]
I think we can work on this later, this need some sort of planning, closing it as of now
