### ISSUE TITLE
[Feature] Greeting on Issue Close

### ISSUE THREAD

**Issue by thevijayshankersharma** [pooranjoyb/popShop#241]
### Description

The feature would allow project managers or team leads to define a template for the closing greeting message. This template could include variables such as the issue ID, title, and the name of the user who resolved it. When an issue is marked as closed, the system would automatically populate this template with relevant information and post it as a comment within the issue thread.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @thevijayshankersharma! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Not needed. :/ 
We appreciate more valuable issues :) @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
@pooranjoyb I can also do for auto comment on PR raised or closed, closing old issues or PRs. If you want to add it in your repo then tell me I would like to do it.

**Comment by pooranjoyb** [comment]
That already exist :/

**Comment by thevijayshankersharma** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/109781385/5229c44e-52ce-4624-a6a0-229b343e1f0f)

you have only or isses and PR raised and on PR merge

**Comment by pooranjoyb** [comment]
> you have only or isses and PR raised and on PR merge

Yes i understand but there are some more issues on priority. work on them if you really wanna contribute :/

**Comment by thevijayshankersharma** [comment]
OK
