### ISSUE TITLE
[Refactor] Show the real-data from database for `Orders`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#248]
### File Name
`pages/Orders/MyOrders.tsx`

### Tasks 
Change the static data to real-data from database.

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by SandipGyawali** [comment]
@pooranjoyb i want to work on it can you assign me. Quite familier with the code bse too.

**Comment by masterboy376** [comment]
Hello @pooranjoyb I would like to work on this issue under gssoc'24.

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this issue

**Comment by pooranjoyb** [comment]
Update ? @SandipGyawali

**Comment by SandipGyawali** [comment]
Ok

**Comment by SandipGyawali** [comment]
hey @pooranjoyb 

![image](https://github.com/pooranjoyb/popShop/assets/66510112/152f5bfb-7596-46a8-92f1-c26afc0bfbb4)

the orders sections doesnot contain the product names, am i targetting to the correct table data ??

**Comment by SandipGyawali** [comment]
the pull request has been added to the previous commit.

#250

**Comment by SandipGyawali** [comment]
@pooranjoyb you forgot to close this the pull request was merged of mine contained this commit too,
