### ISSUE TITLE
[BUG] The cart prive in the navbar does not get updated as we add items

### ISSUE THREAD

**Issue by vansh-sardana** [pooranjoyb/popShop#249]
### Description

On adding 1,2 or more items to the cart, the cart details in the navbar does not get updated. The cart total remains $$999. It needs to be fixed.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/107904311/fcae6144-e971-46f6-b40f-7ac2cd27293c)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @vansh-sardana! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
Go ahead @vansh-sardana, let me and @pooranjoyb know if you need any help
