### ISSUE TITLE
[Feature] Add visibility icon

### ISSUE THREAD

**Issue by AkhilaSunesh** [pooranjoyb/popShop#252]
### Description

![image](https://github.com/pooranjoyb/popShop/assets/140897461/86524005-0dd8-4148-8a90-0fd7f939c199)
Location: signup and login page 
So  that users can view the passwords they type without any difficulty.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @AkhilaSunesh! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@AkhilaSunesh updates?

**Comment by AkhilaSunesh** [comment]
In progress, I will submit it tomorrow itself. I have an exam tomorrow.
