### ISSUE TITLE
💻🔧Create a workflow using Git Actions, this workflow will check Lint errors and Type errors in the changes of Pull request.

### ISSUE THREAD

**Issue by mansi104-ai** [pooranjoyb/popShop#254]
### Description

I want to add lint and type errors checking in the pull requests of the repository, so , every time you want to check the lint and type errors in the repo , go to github actions -> workflows, then simply click on the workflow you want to run , it will show the errors there are in the changed code

I will make a .yml file under .github folder -> workflows , it will contain all the information about the workflow

Please assign me this issue under GSSOC'24

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/118623172/6f766810-e3e2-49c4-993b-953b49ddc4b1)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @mansi104-ai! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Not needed. many people dont use linter :/
Please look for other issues.
