### ISSUE TITLE
[BUG]: No checks applicable

### ISSUE THREAD

**Issue by abckhush** [pooranjoyb/popShop#259]
### Description

There are two bugs I would like to fix. 
1. When the product is added to the cart, there is no requirement for size. Without the size being selected, it is being added to the cart. I want to add a validation check for that.
2. After checkout, the cart should be empty. Even after checkout, the cart shows all the items which were just purchased. I would like to add a validation check for that as well.

Kindly assign me this issue under GSSoC'24 with an appropriate level.

### Screenshots

Bug1
![image](https://github.com/pooranjoyb/popShop/assets/127378920/fa573946-a77a-4f8e-95b2-47c5fe9c2203)

Bug2
![image](https://github.com/pooranjoyb/popShop/assets/127378920/85294685-5bc5-4b28-94a9-d090fb0b7ae8)
![image](https://github.com/pooranjoyb/popShop/assets/127378920/4e3c747f-29a4-409b-8f66-403c55fa9163)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @abckhush! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb  I would like to work on this issue under gssoc'24

**Comment by pooranjoyb** [comment]
Assigned to @abckhush based on fcfs basis. @masterboy376 next on the line :)
