### ISSUE TITLE
Enhancements for improved and cohesive user journey and password security 

### ISSUE THREAD

**Issue by ShreshthaSodhia** [pooranjoyb/popShop#26]
Creating pages for non-functional links in the footer to streamline navigation.
Enforcing password restrictions so that users create more secure passwords
When we view cart contents, we cant go back to product page when clicking on it, so we need to enable redirection from the cart to respective product pages to enhance user experience.
Implement a responsive design strategy to ensure optimal viewing and interaction across devices.
Redesign the navbar to adhere to UI principles and improve overall aesthetics.

**Comment by pooranjoyb** [comment]
- First one is already done. This is already Error Page
- For password restriction we will assign this to you once the zod-validation bug is fixed. We can assign you for that. 
- Rest of the things that you mentioned will be taken care a t a later stage. :)

Do lmk if you wanna work in no. 2 @ShreshthaSodhia

**Comment by ShreshthaSodhia** [comment]
Yes I will work on the password restriction once the validation is fixed. Please assign it to me

**Comment by pooranjoyb** [comment]
Hii @ShreshthaSodhia the zod validation is fixed, you can work on password patterns while signup. 
Use Regex for validation, You are free to change/update the `Signup Schema` but do not change the `Login Schema` as we need to login with `admin` creds

**Comment by ShreshthaSodhia** [comment]
Noted, thank you!

**Comment by pooranjoyb** [comment]
Update? @ShreshthaSodhia

**Comment by ShreshthaSodhia** [comment]
on it! will be done by the weekend

**Comment by pooranjoyb** [comment]
For `level1` issues you only get a day :/

**Comment by ShreshthaSodhia** [comment]
Hi! I'm in the middle of exams so I couldn't complete it
I'll do it before the weekend but its up to your discretion to assign it to someone else if I've violated rules. Sorry for the same

**Comment by amanjaiswal7236** [comment]
Can I work on this issue?

**Comment by pooranjoyb** [comment]
@amanjaiswal7236 Go ahead :)
