### ISSUE TITLE
[Feature] Add page for Buyer detail

### ISSUE THREAD

**Issue by MuraliDharan7** [pooranjoyb/popShop#260]
### Description

I want to add page for buy. When the user click buy button it needs to be direct to the page where the users can give their details for their order.

Please assign this to me under GSSoC'24.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/130668745/bd6044e5-8616-4130-8f00-8f464a121ad6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @MuraliDharan7! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb I would like to work on this issue under gssoc'24

**Comment by pooranjoyb** [comment]
But user has a profile for their information right?
Or do you mean address?

**Comment by MuraliDharan7** [comment]
I meant the Checkout page, where we give all the details to place an order.

**Comment by Mahitej28** [comment]
@MuraliDharan7 the checkout page already exists can you brief us what exactly do you want to add in the checkout page, please share the design file before working

**Comment by MuraliDharan7** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/130668745/a77ec804-f07f-49e2-ab0f-a23d37c80fcb)


Let's take the above image, When I click the Buy button it is redirecting me to this page, and I am able to order easily not going to card and placing order.

**Comment by pooranjoyb** [comment]
@Mahitej28 @AjayAsnani Please have a look and suggest a workflow :)

**Comment by AjayAsnani** [comment]
Give your detail workflow @MuraliDharan7

**Comment by MuraliDharan7** [comment]
> Give the detail workflow of the process

1.Customer proceeds to checkout, enters billing and shipping information, selects a preferred shipping method.
2. Customer chooses a payment method (credit card, etc.), reviews order details and total cost, confirms purchase.
3. Order is processed, payment is verified, customer receives confirmation email with order details and estimated delivery timeframe.

**Comment by pooranjoyb** [comment]
Hey @MuraliDharan7 can we do these steps in a modal?

**Comment by pooranjoyb** [comment]
closing as no updates.
