### ISSUE TITLE
[BUG] Github error

### ISSUE THREAD

**Issue by AkhilaSunesh** [pooranjoyb/popShop#262]
### Description

In the pull request there are spell errors

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/140897461/e3144737-a3eb-4f70-849d-c8f2532a5c17)

### Any additional information?

Kindly assign me this issue.

**Comment by pooranjoyb** [comment]
Congratulations, @AkhilaSunesh! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@AkhilaSunesh thank you for pointing it out, but we can't assign people for one-line errors, please work on some other issue or pr.
