### ISSUE TITLE
[Feature] Auth implementation 

### ISSUE THREAD

**Issue by mukilan2815** [pooranjoyb/popShop#264]
### Description

I can implement auth in this ecommerce. Assign me under GSSOC'24 level 3 as this is backend 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/71129858/d32efed8-ff5d-46ee-bc06-98fa18cd3596)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @mukilan2815! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@mukilan2815 we already have someone working on it :), kindly search for another issue.
