### ISSUE TITLE
Add Google OAuth

### ISSUE THREAD

**Issue by masterboy376** [pooranjoyb/popShop#265]
### Description

This issue aims at creating a Google OAuth feature using google cloud and supabase. 
I am a Gssoc'24 contributor and would like to contribute. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @masterboy376! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
Hello @pooranjoyb I would like to work on this under gssoc'24.

**Comment by pooranjoyb** [comment]
yes go ahead
