### ISSUE TITLE
[BUG]: My order `Views`button is not working

### ISSUE THREAD

**Issue by abckhush** [pooranjoyb/popShop#266]
### Description

On clicking the view button in my orders, invoice of that product should be visible but that button is doing nothing at the moment. I would like to add the functionality to that button.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/127378920/2c751f46-c7cb-4667-9279-31419ed0c995)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @abckhush! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
yes go for it

**Comment by abckhush** [comment]
Order Detail Page?
I was thinking of a popup of the invoice. 
![image](https://github.com/pooranjoyb/popShop/assets/127378920/ccd60258-1667-4432-974e-2b19a8340821)
I need to change the appearance, but this is the idea.


If you want to redirect, I can do that. Which is the order detail page?

**Comment by abckhush** [comment]
Hi @pooranjoyb Kindly tell me

**Comment by pooranjoyb** [comment]
Yes Popup will  be good 👍🏼
