### ISSUE TITLE
[Feature] Wishlists 

### ISSUE THREAD

**Issue by Jasleen1210** [pooranjoyb/popShop#267]
### Description

Id like to add a button to add clothes into a folder separate than cart called "wishlist"/"favorites"/"save for later"

Each clothing item shall have a bookmark/heart option that will store it in the wishlist of that particular user.
Every major ecommerce site has one of these and its very handy to save stuff for later.

Please assign this issue to me under gssoc'24

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Jasleen1210! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes we can go for this :)

**Comment by AjayAsnani** [comment]
> @pooranjoyb @AjayAsnani let me know your thoughts on this!

Yes it's a good idea

**Comment by pooranjoyb** [comment]
Any updates? @Jasleen1210

**Comment by Jasleen1210** [comment]
@pooranjoyb  Hi! its under progress, i am facing certain issues while setting up the backend as im not very familiar with it, but im almost there and ill get back to you soon! 

Also, do you have any suggestions for where you'd like for the add to wishlist (heart icon) to be placed on the product page?

**Comment by pooranjoyb** [comment]
> @pooranjoyb Hi! its under progress, i am facing certain issues while setting up the backend as im not very familiar with it, but im almost there and ill get back to you soon!
> 
> Also, do you have any suggestions for where you'd like for the add to wishlist (heart icon) to be placed on the product page?

Haan you can do :) 🚀

**Comment by pooranjoyb** [comment]
Hii @Jasleen1210 any updates?

**Comment by UtkarshBirla28** [comment]
@pooranjoyb if no one is working on this assign it to me please

**Comment by pooranjoyb** [comment]
> @pooranjoyb if no one is working on this assign it to me please

Go ahead 🚀 @UtkarshBirla28

**Comment by UtkarshBirla28** [comment]
@pooranjoyb sir i have a question where do u want me store whislist data ? in local storage ? Cookies ?

**Comment by pooranjoyb** [comment]
> @pooranjoyb sir i have a question where do u want me store whislist data ? in local storage ? Cookies ?

Use Redux, We already have that setup.
