### ISSUE TITLE
[Feature] Ui for `Profile` Page

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#269]
### Description

@pooranjoyb 

we can design beautiful ui for profile route

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/77a01012-e087-4a08-907f-a79a7ddbcfda)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@dhruv8433 do you mean you want to add a loader or what?, please explain in detail.

**Comment by dhruv8433** [comment]
@Mahitej28 

i want to design ui page for profile section something like this,
where user's  order and everything displayed

![image](https://github.com/pooranjoyb/popShop/assets/114583978/16e279f5-a3aa-43c6-8f74-5b5e314ad28d)

**Comment by Mahitej28** [comment]
> Profile is fine I guess. We can revamp the current UI and not change it completely I'd say. @dhruv8433

Exactly the current UI is good if u want you can just do modifications and share a figma design file with us of the ui

**Comment by dhruv8433** [comment]
Thank you @Mahitej28

**Comment by pooranjoyb** [comment]
Updates ? @dhruv8433

**Comment by dhruv8433** [comment]
@pooranjoyb 

what about kind of this...

![image](https://github.com/pooranjoyb/popShop/assets/114583978/cb53d2d9-5bd5-4715-b8cf-ee6d47099013)

**Comment by pooranjoyb** [comment]
Seems kinda good tho :)
Your thoughts @Mahitej28 @AjayAsnani ?

**Comment by AjayAsnani** [comment]
Yes looks good can go ahead with this.

**Comment by pooranjoyb** [comment]
Update @dhruv8433 ?

**Comment by dhruv8433** [comment]
It will competed till tommorrow
