### ISSUE TITLE
Adding carousel or pagination to the our products section

### ISSUE THREAD

**Issue by anshulsoni4** [pooranjoyb/popShop#27]
![image](https://github.com/pooranjoyb/popShop/assets/74638335/61b7f565-7b60-4734-b67b-88e8b1248ba2)

**Comment by pooranjoyb** [comment]
Yes! Nice thought :)
Go for it 🚀 @anshulsoni4

**Comment by anshulsoni4** [comment]
> Yes! Nice thought :) Go for it 🚀 @anshulsoni4

thanks, on it

**Comment by pooranjoyb** [comment]
Hey @anshulsoni4 Finish up the `Carousel` by tomorrow EOD.

**Comment by anshulsoni4** [comment]
> Hey @anshulsoni4 Finish up the `Carousel` by tomorrow EOD.

alright, on it

**Comment by pooranjoyb** [comment]
Seems like no update from past 3 days, hence closing it :/
