### ISSUE TITLE
[BUG] sibtotal shows `NaN`

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#270]
### Description

@pooranjoyb 

check this out,
even items in cart the subtotal value shows NaN

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/114583978/a27b3180-d011-4e63-af15-3cf0b98dd199)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Fix this glitch :) @dhruv8433
