### ISSUE TITLE
[Feature] Make terms and conditions a mandatory requirement while sign up.

### ISSUE THREAD

**Issue by AkhilaSunesh** [pooranjoyb/popShop#272]
### Description

 Make terms and conditions a mandatory requirement while sign up by inserting a checkbox.
![image](https://github.com/pooranjoyb/popShop/assets/140897461/25a52f9e-a026-4edc-b35e-1a6157cc22ee)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @AkhilaSunesh! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
No need as of now.
