### ISSUE TITLE
[Feature] Add customer feedback form

### ISSUE THREAD

**Issue by Khushi-Pushkar** [pooranjoyb/popShop#273]
### Description

Hey @pooranjoyb  . I am a GSSoC'24 Contributor.

I'd like to contribute to your project by adding a customer feedback form
Kindly assign this issue to me.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Khushi-Pushkar! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I guess we already have the FAQ and Contact section and i feel we can skip this :)
