### ISSUE TITLE
[Feature] password visibility toggle

### ISSUE THREAD

**Issue by Rohitha-pudu** [pooranjoyb/popShop#274]
### Description

adding password toggle in login and sign up

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by AjayAsnani** [comment]
Go ahead @Rohitha-pudu

**Comment by pooranjoyb** [comment]
Sorry @Rohitha-pudu I guess we already have this implemented.
