### ISSUE TITLE
[BUG]: No functionality to the `Apply` Coupon Button

### ISSUE THREAD

**Issue by abckhush** [pooranjoyb/popShop#276]
### Description

On clicking the apply button, no discount is being applied.
The functionality I would like to add:

1. Coupon Validation: When the user clicks the "Apply" button, validate the coupon code. 
2. Apply Discount: If the coupon is valid, discount the total price of the items in the cart.
3. Feedback to User: Popup to show how much they are saving.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/127378920/dd8334f6-8f3c-4995-a068-de793fd6c90b)

### Any additional information?

I would like to know do you want me to hardcode the coupons?

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @abckhush! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by AjayAsnani** [comment]
We will discuss about this and let you know @abckhush

**Comment by pooranjoyb** [comment]
Hii @abckhush I think we can Implement that. Do one thing, use a static coupon and a discount `Coupon object -> with a name and discount value` as of now and on applying this  coupon the discount should be applied on total :)

**Comment by pooranjoyb** [comment]
Update @abckhush ?

**Comment by abckhush** [comment]
Yes I'm working on it

**Comment by pooranjoyb** [comment]
> Yes I'm working on it

Raise a PR by EOD.
