### ISSUE TITLE
[Feature] Add Dark Mode

### ISSUE THREAD

**Issue by GUNJESH843** [pooranjoyb/popShop#277]
### Description

Implementing a dark mode option to enhance user experience, especially in low-light environments. Considerations include user preferences, accessibility, and consistency with existing UI themes.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @GUNJESH843! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by AjayAsnani** [comment]
I don't think we will need Dark mode @GUNJESH843 
@Mahitej28 @pooranjoyb what are your views?

**Comment by pooranjoyb** [comment]
Naah, same thoughts, as of now next priority on the line is the `Admin Dashboard` I think we should go with that. @AjayAsnani
