### ISSUE TITLE
[BUG] GFooter Improvement

### ISSUE THREAD

**Issue by aanchalpahuja18** [pooranjoyb/popShop#279]
### Description

Footer Hover effects can be enhanced further

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/136963878/848784ed-be89-4e44-900d-49be78510f5b)

**Comment by pooranjoyb** [comment]
Congratulations, @aanchalpahuja18! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by aanchalpahuja18** [comment]
@pooranjoyb Kindly assign this issue to me I want to solve it.

**Comment by pooranjoyb** [comment]
Hii @aanchalpahuja18 we can drop this issue for now as this is too irrelevant. Meanwhile I am creating another issue to fix a bug in the Profile Screen. LMK if you wanna wok onto that.

**Comment by aanchalpahuja18** [comment]
@pooranjoyb thanks for responding I would like to work on the issue.

**Comment by aanchalpahuja18** [comment]
@pooranjoyb Kindly let me know about the issue you want to be solved

**Comment by pooranjoyb** [comment]
> @pooranjoyb Kindly let me know about the issue you want to be solved

Have a look on pinned issues.

**Comment by aanchalpahuja18** [comment]
@pooranjoyb all the issues have been assigned to someone you said that you are creating another issue so I would like to work on that.

**Comment by pooranjoyb** [comment]
> @pooranjoyb all the issues have been assigned to someone you said that you are creating another issue so I would like to work on that.

Hii @aanchalpahuja18 you can do one thing, can you research if you can implement the functionality to update the profile picture of the user?

Create the issue for the same.
- Use the current DP for the users where there isn't any dp in supabase db.
- else allow the user to upload their dp and save it to bucket and link it to users table accordingly. 

will be of `level3` issue fr.
