### ISSUE TITLE
[BUG] Update Profile Details

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#281]
### Description

Okay so when we `Signup` using Google OAuth, the gender and phone number is not fetched from the OAuth response. We need to allow the user to manually update these in their profile. 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/6b145b39-016c-41c5-877a-2c27357d8b44)

### Any additional information?

Currently `Edit Profile` doesnot allow change in `Gender` and `Phone Number`, we need to update this and change the respective userData in Supabase. 

![image](https://github.com/pooranjoyb/popShop/assets/90945182/2fc98a4e-914b-4411-a436-f9f0932fbc54)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by bhuvangoel04** [comment]
Please assign me this issue.

**Comment by pooranjoyb** [comment]
Go for it @bhuvangoel04 🚀
