### ISSUE TITLE
[Feature] Initiate UI Admin Dashboard

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#282]
### Description

We are almost done with User Portal with almost all the features of an e-Commerce website. 

Now we are planning to go ahead with the `Admin Dashboard` so that we can manage `Users` and `Orders` directly though the `Admin Portal`

### Tasks : 
- Create the UI for Admin Dashboard

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/88b403e4-b95f-4346-b17e-a76b0e1d4262)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
hello @pooranjoyb I would like to work on this issue

**Comment by pooranjoyb** [comment]
Go for it @masterboy376 🚀

**Comment by AjayAsnani** [comment]
Make sure the UI should be completely responsive @masterboy376 Double check for it.

**Comment by pooranjoyb** [comment]
@masterboy376 hii, whats the update? 
This is on priority right now, possibly blocking all other major issues. Please drop the PR by EOD.

**Comment by masterboy376** [comment]
I am almost done with header and sidebar of admin dashboard

**Comment by pooranjoyb** [comment]
> I am almost done with header and sidebar of admin dashboard

Cool, please complete this on priority :)

**Comment by pooranjoyb** [comment]
Hey @masterboy376 been 5 days now. Please give an update. This is a blocker to many other issues now.

**Comment by masterboy376** [comment]
@pooranjoyb actually I am out of station now I be back on 8th July. If needed you can assign the issue to someone else at the time.
