### ISSUE TITLE
[Feature] Subscription Feature

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#284]
### Description

Integrate an API (use a template) to mail users that they've been subscribed to PopShop and also save the subscribers information in supabase.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/d40206a6-4301-452c-b142-a5f03be58d18)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this issue

**Comment by pooranjoyb** [comment]
Go for it @dhruv8433 🚀

**Comment by dhruv8433** [comment]
Thank you @pooranjoyb

**Comment by dhruv8433** [comment]
@pooranjoyb 

please add me in supabase so i can make table for `Subscribers`

**Comment by pooranjoyb** [comment]
Yes here you go! sent invitation in your mail :)

**Comment by dhruv8433** [comment]
@pooranjoyb 

dhruvrsoni04@gmail.com

**Comment by pooranjoyb** [comment]
> @pooranjoyb
> 
> [dhruvrsoni04@gmail.com](mailto:dhruvrsoni04@gmail.com)

done
