### ISSUE TITLE
[BUG] Item-stays-in-cart-after-quantity-turns-zero

### ISSUE THREAD

**Issue by bhuvangoel04** [pooranjoyb/popShop#286]
### Description

The item must be deleted from the cart automatically when user decreases the quantity to zero.
## Checklist
- [X] I want to work on this issue.
- [X] I have checked the existing issues.
- [X] I am a GSSoC 2024 contributor.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/156914582/44342588-21d9-410b-8628-5f5ad70d524c)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @bhuvangoel04! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @bhuvangoel04 I think we should modify the approach, try to make the initial value of the Counter to be 1 and not 0 so that 0 is not available to choose.
