### ISSUE TITLE
[Feature] Adding functionality to the buy now button.

### ISSUE THREAD

**Issue by bhuvangoel04** [pooranjoyb/popShop#288]
### Description

When the user clicks on Buy now button, the user is redirected tot the checkout page.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/156914582/931e3f8f-dac5-408a-9903-7b5948d8cad6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @bhuvangoel04! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Please explain the workflow of how do you plan to execute this. @bhuvangoel04

**Comment by bhuvangoel04** [comment]
Here the checkout button is only fetching data from the cart. We can pass the product data to the Checkout component through navigation to modify the Checkout component to handle both fetching data from the cart and directly from the product page when the user clicks the "Buy Now" button.
First pass the product data when navigating to the Checkout component and then
Check for the passed product data and handle the state accordingly.

**Comment by bhuvangoel04** [comment]
@AjayAsnani Placing an order requires data like size and the item to be bought.
Also ,If the user is buying directly, the cart items are not cleared from the database after placing the order so placeOrder will also be modified.

**Comment by AjayAsnani** [comment]
Ohk sounds good to me.
@pooranjoyb @Mahitej28 your words on this.

**Comment by AjayAsnani** [comment]
Go ahead @bhuvangoel04 and keep updating.

**Comment by bhuvangoel04** [comment]
I will try to make a pull request by end of tomorrow.
Until then can you please add gssoc labels to it and assign me.

**Comment by AjayAsnani** [comment]
Don't worry about labels we will take care of that you just make sure that work is completed without any errors.
Also, look for responsiveness with what you are implementing.

**Comment by bhuvangoel04** [comment]
Just level1 for so many changes?
Please recheck if you can atleast change it to level2
