### ISSUE TITLE
Adjust Footer for Mobile View

### ISSUE THREAD

**Issue by m3kvt** [pooranjoyb/popShop#292]
### Description

I would like to align the footer contents to center so as to enhance its readability and looks. It will also utilize the space in the right side of the footer.

### Screenshots

before:
![image](https://github.com/pooranjoyb/popShop/assets/98379619/96dc1210-ff83-4756-9846-c00ad1bb5e87)

after:
![image](https://github.com/pooranjoyb/popShop/assets/98379619/c26dd34c-0d39-41ed-8930-72506ae1a023)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @m3kvt! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
This centering can be done in other issue :/
