### ISSUE TITLE
[Feature] Dark Mode for the website

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#293]
### Description

I want to implement the dark mode for the website 
So that user can switch between dark and light mode according to his choice 

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Not planned as of now. You can check out the issue in a day or two. We are building the Admin Dashboard, you might work onto that. @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure
