### ISSUE TITLE
[Feature] Want to add a fade up and fade in animation 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#294]
### Description

I want to add an animation to the cards 
Like when user scrolls down then he see the card will pop up just right now with some amazing animation which absolutely looks good 

### Screenshots

https://github.com/pooranjoyb/popShop/assets/118350936/39bceac0-3753-4394-8151-b09297884669

Example

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I think that's not needed as we already have Framer Motion initialized.
