### ISSUE TITLE
Enhancement of the footer

### ISSUE THREAD

**Issue by jayanththalla** [pooranjoyb/popShop#295]
### Description

Change the footer into official page of the fashion page 

please assign me @pa

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/121346142/46f7242f-2b58-4414-b146-6b0fa9f248ca)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @jayanththalla! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
The issue is unclear. Please be specific about the change you want to make :/
