### ISSUE TITLE
[BUG] logo in not visible

### ISSUE THREAD

**Issue by root-0101** [pooranjoyb/popShop#296]
### Description

The logo in the contact section, shop, admin is not visible

### Screenshots

![Screenshot 2024-07-04 213327](https://github.com/pooranjoyb/popShop/assets/142779809/7094ed46-1552-4f8c-bcbf-98d7e1dd8935)
![Screenshot 2024-07-04 213909](https://github.com/pooranjoyb/popShop/assets/142779809/76394893-bd1d-4ecc-ab49-cf22cbbd5d0a)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @root-0101! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
One issue at a time @root-0101 :)

**Comment by Chhaya-g** [comment]
@pooranjoyb could you please assign me this issue under GSSOC'24.

**Comment by pooranjoyb** [comment]
No update hence closing.
