### ISSUE TITLE
[Feature] Add upload profile image button

### ISSUE THREAD

**Issue by root-0101** [pooranjoyb/popShop#297]
### Description

Adding an upload profile image would be a great feature, it provide user a personal touch and enhance user experience

### Screenshots

![Screenshot 2024-07-04 213909](https://github.com/pooranjoyb/popShop/assets/142779809/66e19fa4-26cb-4af0-9ffb-e37e8c8c4a24)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @root-0101! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I was also planning this issue. You'll have to handle and work on the database too. LMK your email address to allow access to supabase 👍🏼 @root-0101

**Comment by pooranjoyb** [comment]
No update hence removing assignment.

**Comment by abckhush** [comment]
I want to try to work on this @pooranjoyb

**Comment by abckhush** [comment]
Hi @pooranjoyb How can I access the database?

**Comment by pooranjoyb** [comment]
Drop me your mail @abckhush

**Comment by abckhush** [comment]
kalra.khushi12@gmail.com

**Comment by pooranjoyb** [comment]
> [kalra.khushi12@gmail.com](mailto:kalra.khushi12@gmail.com)

Sent invitation to your mail. Please check.

**Comment by abckhush** [comment]
Got it. Credentials admin & Admin@123 are not working.

**Comment by pooranjoyb** [comment]
> Got it. Credentials admin & Admin@123 are not working.

Hiii @abckhush 
Supabase is down today. Check its status here https://status.supabase.com/

![image](https://github.com/user-attachments/assets/0bf4bb28-cf51-4686-8cd7-8ff4a287a9cf)
