### ISSUE TITLE
Buy now button redirection

### ISSUE THREAD

**Issue by root-0101** [pooranjoyb/popShop#298]
As when user click on buy now button it will redirect it directly to payment page, but the current scenario is it does not navigate to payment page

![Screenshot 2024-07-04 214625](https://github.com/pooranjoyb/popShop/assets/142779809/aac4829f-e104-43fa-b48d-cdb6b0256b06)

**Comment by pooranjoyb** [comment]
Congratulations, @root-0101! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Merged in #289
