### ISSUE TITLE
Zod Validation for User Auth

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#3]
### Tasks
 
- Create a file called `schema.ts` inside the `/src/utils/` directory and create the schema for both **Sign up** and **Login**
- Refer to https://zod.dev for more information.
- Validate the Form using the Zod validation rules
- Remove the Alerts and Display the Validation Errors just below the Form Field. 

Create the PR to `dev`

**Comment by SandipGyawali** [comment]
@pooranjoyb is it open to contribute ??

if yes can you assign me this issue under a label.

**Comment by Divyanshi1002** [comment]
hey @pooranjoyb ,
Please assign me this issue . I have previously worked on similar projects.

**Comment by anwesha2002** [comment]
hey @pooranjoyb 
I am a GSSOC'24 contributor.Can you please assign be the issue, will be able to fix it.

**Comment by pooranjoyb** [comment]
Hii @SandipGyawali you'll have 24 hours to finish this issue :) All the best 👍🏼

**Comment by SandipGyawali** [comment]
ok, sure

**Comment by pooranjoyb** [comment]
Fixed in #8
