### ISSUE TITLE
[Feature] SuperAdmin Dashboard

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#300]
### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/3dc6cab9-687b-4028-b8fc-dc9d0a0026ad)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/90945182/2458b9e7-8c4b-40b4-b160-3faa15fc2453)

Clone this or take this as an inspiration

**Comment by abckhush** [comment]
For now, these will be hardcoded features?

**Comment by pooranjoyb** [comment]
Yeh filhaal toh hardcoded will do. But maintain the UI as given, or if you have better UI, drop it here in the comments. @abckhush

**Comment by abckhush** [comment]
@pooranjoyb I'll try to implement this dashboard only.
![image](https://github.com/pooranjoyb/popShop/assets/127378920/65daeeb2-ce46-4d6e-8aee-290c9c5039d7)
If you are satisfied this, kindly assign me the issue.

**Comment by pooranjoyb** [comment]
Cool, use some graphs/pie charts. kinda looks good for dashboard uk :) @abckhush

**Comment by abckhush** [comment]
I'll try my best.
