### ISSUE TITLE
[Feature] Display Orders in SuperAdmin

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#301]
### Tasks

Fetch all the orders from supabase and show them in Admin Dashboard.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/6f0594ec-99a0-41d5-ac66-aa2d05efd9e3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by UtkarshBirla28** [comment]
@pooranjoyb Assign it to me sir i will resolve it ASAP

**Comment by pooranjoyb** [comment]
Hii @UtkarshBirla28 
Password and username for superadmin is 

popshop-admin

**Comment by UtkarshBirla28** [comment]
@pooranjoyb 

username : admin
password : popshop

this is not working sir

**Comment by UtkarshBirla28** [comment]
@pooranjoyb 
username: admin
password:Admin@123

is working

**Comment by UtkarshBirla28** [comment]
@pooranjoyb and sir where is super admin portal ?

on which route ?

**Comment by pooranjoyb** [comment]
> @pooranjoyb and sir where is super admin portal ?
> 
> on which route ?

/admin

**Comment by UtkarshBirla28** [comment]
![Screenshot (166)](https://github.com/pooranjoyb/popShop/assets/96072228/98454f48-8419-4946-bcd8-7ceff5e94b1b)

@pooranjoyb I have a question you want all the details in order dashboard ??

and should i make a table for them or display in card like component ??

**Comment by pooranjoyb** [comment]
Table would be fine :) @UtkarshBirla28

**Comment by UtkarshBirla28** [comment]
![Screenshot (171)](https://github.com/pooranjoyb/popShop/assets/96072228/d1426991-5f58-4e7c-8e2d-d21892894c08)


@pooranjoyb Will this work ??

**Comment by UtkarshBirla28** [comment]
@pooranjoyb  Frontend is not cup of my tea so it's  pretty difficult to structure tables.

**Comment by pooranjoyb** [comment]
Hii @UtkarshBirla28 you could've used Daisy UI Tables. And no need to show the images. 

check this out https://daisyui.com/components/table/

**Comment by UtkarshBirla28** [comment]
https://github.com/pooranjoyb/popShop/assets/96072228/32723ecd-db6e-4521-8a99-560503ce9858


@pooranjoyb Is this good ??
