### ISSUE TITLE
Orders getting added individually into the cart

### ISSUE THREAD

**Issue by UtkarshBirla28** [pooranjoyb/popShop#302]
### Description

Instead of Increasing the quantity order is getting added individually into the cart 

I am a GSOC24 contributor

### Screenshots

https://github.com/pooranjoyb/popShop/assets/96072228/8ce2db02-ab24-4d8b-8029-ea58ac505baa

**Comment by pooranjoyb** [comment]
Congratulations, @UtkarshBirla28! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes finish up the previous issue and then you can work onto it 🚀 @UtkarshBirla28

**Comment by Tanishashrivas** [comment]
Can you assign this issue to me under gssoc?

**Comment by pooranjoyb** [comment]
Go for it @Tanishashrivas
