### ISSUE TITLE
[Feature] Add product to Products table (SuperAdmin Portal)

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#303]
### Tasks 

- You'll first have to take the uploaded image and add it to Images bucket.
- Fetch the Image link from url and add it to Products Table
![image](https://github.com/pooranjoyb/popShop/assets/90945182/0c2b22d6-ad48-426c-aacf-30dbd8042209)

Here is the Products Table : 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/77826c14-c1be-4ece-b41e-d9653c7fbeb4)

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/90945182/d66734b1-7808-4555-92bb-27432f46bdf5)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Tanishashrivas** [comment]
I would like to work on this issue, also seeking the details if u can elaborate it further but pls assign it to me :)

**Comment by pooranjoyb** [comment]
Go ahead @Tanishashrivas 🚀

**Comment by pooranjoyb** [comment]
do lmk if you need supabase access.

**Comment by pooranjoyb** [comment]
No update hence assigning it to @Varsani2520

**Comment by Varsani2520** [comment]
@pooranjoyb ,assign me

**Comment by pooranjoyb** [comment]
> @pooranjoyb ,assign me

Done, do lmk if you need supabase access. Drop you email I'll add you to the team :)

**Comment by Varsani2520** [comment]
thank you @pooranjoyb ,i give my best

**Comment by Varsani2520** [comment]
My email id is :varsaniranjani@gmail.com

**Comment by pooranjoyb** [comment]
> My email id is :[varsaniranjani@gmail.com](mailto:varsaniranjani@gmail.com)

Sent invite link to mail 👍🏼

**Comment by Varsani2520** [comment]
ok i got it
