### ISSUE TITLE
Filter not functioning

### ISSUE THREAD

**Issue by UtkarshBirla28** [pooranjoyb/popShop#305]
### Screenshots

https://github.com/pooranjoyb/popShop/assets/96072228/d1a7a05c-9829-4f1c-9405-d09a9593cc41

**Comment by pooranjoyb** [comment]
Congratulations, @UtkarshBirla28! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by masterboy376** [comment]
hello @pooranjoyb I would like to work on this issue

**Comment by pooranjoyb** [comment]
Go ahead :) @masterboy376

**Comment by UtkarshBirla28** [comment]
@pooranjoyb Assign it to me please

**Comment by pooranjoyb** [comment]
> @pooranjoyb Assign it to me please

Next on the line @UtkarshBirla28
