### ISSUE TITLE
INR to USD

### ISSUE THREAD

**Issue by UtkarshBirla28** [pooranjoyb/popShop#306]
### Description

showing price of items in INR but when you click on items they show price in USD

### Screenshots

https://github.com/pooranjoyb/popShop/assets/96072228/4a6faf49-adfe-4a8c-b567-6f12e2edde8e

**Comment by pooranjoyb** [comment]
Congratulations, @UtkarshBirla28! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes This also has to be fixed :)
One issue at a time tho :/ Finish up the issue you are assigned to.

**Comment by UtkarshBirla28** [comment]
@pooranjoyb yes yes sorry just doing it for a friend she will take this issue.

**Comment by pooranjoyb** [comment]
> @pooranjoyb yes yes sorry just doing it for a friend she will take this issue. 

Haha, cool!

**Comment by Tanishashrivas** [comment]
@pooranjoyb I want to work on this issue sir

**Comment by pooranjoyb** [comment]
Go ahead 🚀 @Tanishashrivas

**Comment by UtkarshBirla28** [comment]
@pooranjoyb  @Tanishashrivas  fixing 2 issue in 1 PR ?

so this will be counted as 2 issue or one ?
u will get points for 2 issue right ?

**Comment by pooranjoyb** [comment]
Hii @UtkarshBirla28 This change is literally 1 line. 
We expect some more work for the level 1 badge. So will give one level 2 for both issues in this single PR.

**Comment by UtkarshBirla28** [comment]
@pooranjoyb Ahh okok
