### ISSUE TITLE
[Feature] <Add Featured Seller section in home page>

### ISSUE THREAD

**Issue by arunimaChintu** [pooranjoyb/popShop#309]
### Description

This add featured seller in home page

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Hii @arunimaChintu awesome issue I'd say but this can be done in future. No plans as of now. :/
