### ISSUE TITLE
[Feature] Floating Animation to the Image

### ISSUE THREAD

**Issue by Damini2004** [pooranjoyb/popShop#313]
### Description

Help to grab more user attention.

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/119414762/512bd145-dcaa-478c-8d83-75e5a8ace7c3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Damini2004! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well, I guess this is not needed as of now. Have a look into other issues for Admin Dashboard. @Damini2004
