### ISSUE TITLE
[Feature] Adding an AI Chatbot to the Website

### ISSUE THREAD

**Issue by sanskritisahu21** [pooranjoyb/popShop#315]
### Description

Integrate an AI-powered chatbot into the website to enhance user interaction, provide instant support, and improve overall user experience.

Chatbot Functionality:
Answer common user queries
Provide information about our services/products
Assist users with navigation on the website

Expected Outcomes:
Improved user engagement and satisfaction
Reduced response time for user inquiries
Enhanced ability to gather user data for future improvements

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @sanskritisahu21! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by sanskritisahu21** [comment]
@pooranjoyb Please assign me this issue under gssoc

**Comment by pooranjoyb** [comment]
Hii @sanskritisahu21, How would you plan to execute this? 
If I'm not wrong u mean to integrate a Assistant and not the so called "AI Bot" or Am I missing something?
Please clarify.

**Comment by sanskritisahu21** [comment]
@pooranjoyb Thankyou for assigning me the issue.
No, I'm talking about AI chat-bot. Will create AI flows to answer common user queries, provide information about our services/products, and assist users with website navigation without needing to train a separate assistant.

**Comment by pooranjoyb** [comment]
> @pooranjoyb Thankyou for assigning me the issue. No, I'm talking about AI chat-bot. Will create AI flows to answer common user queries, provide information about our services/products, and assist users with website navigation without needing to train a separate assistant.

Cool Sounds good to me! You can go ahead for this :) @sanskritisahu21 
Use it like a popup beside the `Scroll to Top` button in bottom-right corner of the page.

**Comment by sanskritisahu21** [comment]
okay

**Comment by sanskritisahu21** [comment]
@pooranjoyb sir the react project which you provided is not showing anything in browser , like when I am starting the react project the website is just looking blank and nothing is shown in browser.

**Comment by pooranjoyb** [comment]
> @pooranjoyb sir the react project which you provided is not showing anything in browser , like when I am starting the react project the website is just looking blank and nothing is shown in browser.

Hii @sanskritisahu21 I think you've not read the CONTRIBUTING GUIDELINES. Please have a look on that :)
