### ISSUE TITLE
[Feature] : there is no logo in contact page

### ISSUE THREAD

**Issue by jayanththalla** [pooranjoyb/popShop#317]
### Description

In the contact page, there is no logo in the main page and navbar 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/121346142/4ca1d3d0-4f2a-4ac7-8455-4bba0f07030f)
please assign me @pa

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Actually there is the logo, but somehow this doesnot gets rendered everytime. WE need to refresh it actually.Could you identify this problem and lemme know the fix over here in comments?

@jayanththalla

**Comment by jayanththalla** [comment]
> Actually there is the logo, but somehow this doesnot gets rendered everytime. WE need to refresh it actually.Could you identify this problem and lemme know the fix over here in comments?
> 
> @jayanththalla

after rendering it showing same as previous one

**Comment by pooranjoyb** [comment]
> > Actually there is the logo, but somehow this doesnot gets rendered everytime. WE need to refresh it actually.Could you identify this problem and lemme know the fix over here in comments?
> > @jayanththalla
> 
> after rendering it showing same as previous one

Ok you can fix this :)
