### ISSUE TITLE
[BUG] :filter search not working

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#318]
### Description

here search filter not working

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/137641079/57918f9b-e0db-4378-bb5c-d848bcfa7766)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,please assign this issue to me

**Comment by pooranjoyb** [comment]
> @pooranjoyb ,please assign this issue to me

Hii @Varsani2520 Could you please check, why this feature isn't working?
Actually we had this fixed long ago. Could be some bug, possibly. You can go ahead with this. But do changes in existing code only.

**Comment by Varsani2520** [comment]
thank you @pooranjoyb
