### ISSUE TITLE
Bug: Login with Google button is not working

### ISSUE THREAD

**Issue by SaurabhS55** [pooranjoyb/popShop#32]
Hey there, Login with google button is not working in login page and sign up page. I would like to work on this issue. could you assign this issue to me under GSSOC'24 label ?

**Comment by pooranjoyb** [comment]
Hii @SaurabhS55 before working on that we'd be setup React-Redux. We'll create issues regarding that soon! 
Looking forward to more bug fixes and ui improvements as of now 🚀
