### ISSUE TITLE
[Feature] Want to create a contributors page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#321]
### Description

I want to create a contributors page where users can see the real time contributors and with the number of contributions did by a single user 

### Screenshots

![image](https://github.com/pooranjoyb/popShop/assets/118350936/45e8eceb-ce5c-4eb4-8f9f-473ece826d7a)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well, this is not needed ig :/
