### ISSUE TITLE
[Feature] Want to create the about us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#322]
### Description

I want to create the about us page as the link in the footer is not working correctly  so i want to create the about us page 

### Screenshots

https://github.com/pooranjoyb/popShop/assets/118350936/008059b2-41b5-422c-a1b5-8b9aac712b04

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Not needed as of now :)
Please have a look on the Admin Dashboard related issues. Those are more important now :/
