### ISSUE TITLE
[Feature] Want to add the tilt effect on the header image 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#323]
### Description

I want to add the tilt effect to the header image so that it will interact with users and will make it more dynamic and interactive 

### Screenshots

https://github.com/pooranjoyb/popShop/assets/118350936/b36b59a2-22f1-444f-ae17-94208aec6951
![image](https://github.com/pooranjoyb/popShop/assets/118350936/c3ef4783-9a31-4cca-95ab-92074ec28ae2)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go ahead :) Nice idea tho :) @Ayushmaanagarwal1211

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this
