### ISSUE TITLE
[Feature]  Want to complete the search and filter products functionality 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [pooranjoyb/popShop#324]
### Description

I want to complete the search and the filter functionality for the products 

### Screenshots

https://github.com/pooranjoyb/popShop/assets/118350936/3b8dd4be-2382-4e10-9e24-905fe6c5fecf

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ayushmaanagarwal1211! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @Ayushmaanagarwal1211 this issue is actually done, but not deployed on prod as of now :)
