### ISSUE TITLE
Add Icons To Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [pooranjoyb/popShop#325]
### Description

Hello Project Admin
I would like to add icons to Footer to make website look attractive
Can you assign me this issue under GSSOC'24 @pooranjoyb 

### Screenshots

![IMG_20240710_213050](https://github.com/pooranjoyb/popShop/assets/161804629/6babbf2e-83fc-48a1-b830-246196587d33)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @sailaja-adapa! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes do this in one PR only.

**Comment by sailaja-adapa** [comment]
You mean you want me to add icons to Navbar and footer in one PR @pooranjoyb

**Comment by pooranjoyb** [comment]
> You mean you want me to add icons to Navbar and footer in one PR @pooranjoyb

Yes do it in #315 itself :)

**Comment by sailaja-adapa** [comment]
Yeah okk @pooranjoyb

**Comment by sailaja-adapa** [comment]
@pooranjoyb can you please clarify me why u r Mentioning #315??

**Comment by pooranjoyb** [comment]
Opps sorry, my bad :/

**Comment by sailaja-adapa** [comment]
You want me all the icons and Rate us option in One PR right??

**Comment by sailaja-adapa** [comment]
I will do that no problem @pooranjoyb :)
