### ISSUE TITLE
Add Icons To Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [pooranjoyb/popShop#326]
### Description

Hello Project Admin
I would like to add icons to Navbar
Can you assign me this issue under GSSOC'24 @pooranjoyb 

### Screenshots

![IMG_20240710_213127](https://github.com/pooranjoyb/popShop/assets/161804629/94f6b9f6-486a-4717-8a56-fbd039dae37a)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @sailaja-adapa! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yes you can go ahead. Use `react-icons` for the same :)

**Comment by sailaja-adapa** [comment]
Yeah okk @pooranjoyb :)

**Comment by pooranjoyb** [comment]
Hey @sailaja-adapa What's the update. Been a week now :/

**Comment by sailaja-adapa** [comment]
Sorry @pooranjoyb due to some works I didn't completed task I will raise PR soon

**Comment by pooranjoyb** [comment]
> Sorry @pooranjoyb due to some works I didn't completed task I will raise PR soon

Koi na, do it before someone else takes it  lol :)

**Comment by sailaja-adapa** [comment]
@pooranjoyb Can u assign this to someone else
