### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [pooranjoyb/popShop#327]
### Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @sailaja-adapa! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
You can go ahead with this, but where and how do you plan to keep this? @sailaja-adapa

**Comment by sailaja-adapa** [comment]
I will place this Rate Us option in footer when user click on that it will head to other page @pooranjoyb

**Comment by pooranjoyb** [comment]
> I will place this Rate Us option in footer when user click on that it will head to other page @pooranjoyb

Do one thing, instead of doing that, write something like, support out project and then redirect them to the github repository to star the repo. 

Do this change on the same PR for #315
