### ISSUE TITLE
[BUG] Phone number exceeding more than 10 digit

### ISSUE THREAD

**Issue by UtkarshBirla28** [pooranjoyb/popShop#328]
### Description

![Screenshot (199)](https://github.com/pooranjoyb/popShop/assets/96072228/6dcc9f93-6906-4a17-bd9a-0d355b4f246f)

### Screenshots

![Screenshot (198)](https://github.com/pooranjoyb/popShop/assets/96072228/626d5bb0-418e-4285-b69c-7ce5962c9295)

**Comment by pooranjoyb** [comment]
Congratulations, @UtkarshBirla28! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Cool, use the zod validator to validate these data, you can see the functions are already present, you just need to pass it to validator and show the respective errors.
Check the Signup page for reference. @UtkarshBirla28

**Comment by UtkarshBirla28** [comment]
@pooranjoyb I have a question i have already solved this issue  and want to make a PR request but my previous PR is still open it's not closed yet so should i merge it in that PR only ? because i am not able issue a new PR

**Comment by pooranjoyb** [comment]
> @pooranjoyb I have a question i have already solved this issue  and want to make a PR request but my previous PR is still open it's not closed yet so should i merge it in that PR only ? because i am not able issue a new PR

Yes go ahead :)
