### ISSUE TITLE
[Feature] Floating animation

### ISSUE THREAD

**Issue by Damini2004** [pooranjoyb/popShop#332]
### Description

it will levitate the image

### Screenshots

![image](https://github.com/user-attachments/assets/052daefd-8b32-4a35-8824-dd4b3b54ce89)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Damini2004! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @Damini2004 I guess we already have some animations.
You can work on the Admin Dashboard if you want. Check discussions :)
