### ISSUE TITLE
[Feature] Add login before access admin panel

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#334]
### Description

@pooranjoyb 

we can add one username and password 
and based on that we can validate admin and get access to admin panel

### Screenshots

![image](https://github.com/user-attachments/assets/9957d642-b975-4655-a242-f0b4c81a8676)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
Well @dhruv8433 this looks good to me @pooranjoyb @AjayAsnani let me know your thoughts on this!

**Comment by pooranjoyb** [comment]
Well, there's a login 😅 
Check Discussions. @dhruv8433

**Comment by pooranjoyb** [comment]
> Well, there's a login 😅 Check Discussions. @dhruv8433

We'll possible have to make it `Protected Route` LMK if you wanna work onto that.?

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on that
