### ISSUE TITLE
[Feature] Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [pooranjoyb/popShop#336]
### Description

Docker is a must for open-source projects nowadays as it has its benefits.

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

I will also be updating the docs for it.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Ratangulati! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yup go for it 🚀 @Ratangulati

**Comment by SwetanshuSingh** [comment]
@pooranjoyb if there was an example .env file in the project, that would make it easier to write the dockerfile

**Comment by pooranjoyb** [comment]
> @pooranjoyb if there was an example .env file in the project, that would make it easier to write the dockerfile

read CONTRIBUTING GUIDELINES
