### ISSUE TITLE
[Feature]: Add buy again and cancel order features

### ISSUE THREAD

**Issue by abckhush** [pooranjoyb/popShop#337]
### Description

To re-order the items or to cancel the purchase, no feature is available till now. I would like to add that on My Orders Page.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @abckhush! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @abckhush One issue at a time :/

**Comment by abckhush** [comment]
@pooranjoyb Can I work on this issue now?

**Comment by abckhush** [comment]
@pooranjoyb is there any limit of points for this repo?

**Comment by Yogesh-ok55** [comment]
please assign this to me , i have already contributed to this project so i have better understanding

**Comment by pooranjoyb** [comment]
> @pooranjoyb is there any limit of points for this repo?

Level 3 is Max

**Comment by abckhush** [comment]
No as in some repos have restrictions of contributing only 150points worth PRs. In this, is there any restriction?

**Comment by pooranjoyb** [comment]
> No as in some repos have restrictions of contributing only 150points worth PRs. In this, is there any restriction?

The rules remains the same for all repos. If you're eager to continue, go ahead :)
I mean it's upto you.

**Comment by abckhush** [comment]
![image](https://github.com/user-attachments/assets/e5ac9985-e4ea-49c7-9e31-f925021d0ed4)
I'm sorry for taking your time @pooranjoyb but this mentions that we can create many PRs in a repo except a few and they are not listed or I cant find that's why.

**Comment by pooranjoyb** [comment]
> ![image](https://github.com/user-attachments/assets/e5ac9985-e4ea-49c7-9e31-f925021d0ed4)
> I'm sorry for taking your time @pooranjoyb but this mentions that we can create many PRs in a repo except a few and they are not listed or I cant find that's why.

You can contact the admins in discord. I guess they can guide you with this.
