### ISSUE TITLE
[Feature] Reset Password Feature

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/popShop#338]
### Description

User should receive a follow-up mail to change the password.

Research on this https://supabase.com/docs/reference/javascript/auth-resetpasswordforemail

### Screenshots

![image](https://github.com/user-attachments/assets/11f29b72-b03c-4a09-a9ef-f1d510f96315)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pooranjoyb! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

i would like to work on this issue

**Comment by Elanngo-Madheswaran** [comment]
I would like to join this issue

**Comment by Yashaswi0413** [comment]
@pooranjoyb 
I would like to work on the issue

**Comment by pooranjoyb** [comment]
> @pooranjoyb 
> 
> i would like to work on this issue

Go ahead @dhruv8433

**Comment by Elanngo-Madheswaran** [comment]
can i join @pooranjoyb

**Comment by pooranjoyb** [comment]
Hey @Elanngo-Madheswaran it is based on fcfs.

**Comment by dhruv8433** [comment]
Thank you @pooranjoyb

**Comment by dhruv8433** [comment]
@pooranjoyb 

add me in supabase so i can check password resend email is configured or not and password will chnaged or not

**Comment by pooranjoyb** [comment]
> @pooranjoyb 
> 
> add me in supabase so i can check password resend email is configured or not and password will chnaged or not

Email please.

**Comment by dhruv8433** [comment]
dhruvrsoni04@gmail.com

**Comment by dhruv8433** [comment]
@pooranjoyb 

add me in supabase so i can start work

**Comment by pooranjoyb** [comment]
yes done :) @dhruv8433
