### ISSUE TITLE
[BUG] Dashboard ui in admin panel

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#342]
### Description

we can add dashboard ui and also add the functionality

### Screenshots

![image](https://github.com/user-attachments/assets/c054fffa-8036-43a7-8ffc-cc5a05cc8c29)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,please assign me we can active admin dashboard

**Comment by pooranjoyb** [comment]
Hey @Varsani2520 there's already the ui. you can just integrate the things from supabase. LMK if you wanna go ahead with this

**Comment by Varsani2520** [comment]
@pooranjoyb Yes i want

**Comment by pooranjoyb** [comment]
Any updates? @Varsani2520
