### ISSUE TITLE
[Feature] If user is logged in with google we can display profile picture from it

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#344]
### Description

@pooranjoyb 

if user logged in with google and it have profile picture set in google account 
we can display it in profile image

### Screenshots

![image](https://github.com/user-attachments/assets/9b3e9fb0-2c4c-4410-9431-dfb9f9d7e32f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yup go ahead integrate that too :) @dhruv8433
