### ISSUE TITLE
[Feature] Display transaction from supabase

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#345]
### Description

@pooranjoyb 

we can display real time transaction from supabase 

### Screenshots

![image](https://github.com/user-attachments/assets/0d17d497-adbd-4e4c-8897-0264deedc228)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @dhruv8433 Raise 1 PR for both #344 & this one
