### ISSUE TITLE
[BUG] Make Dashboard Responsive

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#347]
### Description

@pooranjoyb 

we can make dashboard ui responsive so it have better view in responsive devices

### Screenshots

![image](https://github.com/user-attachments/assets/0a465bf1-eb7b-481a-acdc-7884f92fb0a7)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
@dhruv8433 Waiting for #342

**Comment by pahuja-sahil** [comment]
@pooranjoyb I would like to work on this issue .
please assign this issue to me under gssoc 24.
Thank you.

**Comment by pooranjoyb** [comment]
Hey @dhruv8433 you can work on this now 👍🏼
