### ISSUE TITLE
[BUG] Missing Burger Menu for routing in other pages

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#348]
### Description

@pooranjoyb 

check this out,
there are burger menu missing for other routes like `collections`, `products`, `contact us` etc...

### Screenshots

![image](https://github.com/user-attachments/assets/14f23ee9-333e-4d30-8621-d998979dcfaf)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
You can do this in other PR @dhruv8433
