### ISSUE TITLE
[BUG] Filter not working in product

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#349]
### Description

@pooranjoyb 

check this out,
filter is not working after clicking on `Apply` button

### Screenshots

![image](https://github.com/user-attachments/assets/4f93c9d8-f924-4dd5-a01b-6cd1627c8e44)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

please assign me i would like to work on this

**Comment by pooranjoyb** [comment]
Yes fix this bug and also add routes for other pages in Hamburger Menu :) @dhruv8433

**Comment by dhruv8433** [comment]
Ok Thank you @pooranjoyb
