### ISSUE TITLE
Basically Cart is static adding items to cart deleting items and sending products details to the backend ...

### ISSUE THREAD

**Issue by NIveX2169** [pooranjoyb/popShop#35]
If it is possible then i would love to add this functionality where we would click add to cart then we would add/remove and update  items
to cart using redux. what im thinking is to use redux and redux persist when users add items to cart it would immediately changes the ui if everything is fine then would send data to the backend else error dilaog would appear or something like toas type which would tell that we failed to update .... please do tell me if something efficient or more accurate approach is there according to you Thank you ..

**Comment by pooranjoyb** [comment]
refer #36 

We'll create this later after the Authentication state management is done :))
