### ISSUE TITLE
[BUG] There is no logo in the contact main page

### ISSUE THREAD

**Issue by jayanththalla** [pooranjoyb/popShop#351]
### Description

Missing popshop logo in the contact main page 

### Screenshots

<img width="960" alt="image" src="https://github.com/user-attachments/assets/9a4d1cb0-3cf5-42b6-8d02-01b4bb81badd">

### Any additional information?

please assign me @pa

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by pooranjoyb** [comment]
Congratulations, @jayanththalla! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I can see the logo in your ss tho :/
