### ISSUE TITLE
[Feature] Add a google language translator in the website.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [pooranjoyb/popShop#352]
### Description

I wish to add a google language translator.

### Screenshots

![Screenshot 2024-07-20 065125](https://github.com/user-attachments/assets/94ebfd66-d175-4d78-be8d-ea36a3a8c9b8)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @ParnaRoyChowdhury777! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Okay Go ahead :)
Add this in Footer @ParnaRoyChowdhury777

**Comment by pooranjoyb** [comment]
Closing as no update

**Comment by ParnaRoyChowdhury777** [comment]
> Closing as no update

I was occupied with many projects. I can send the PR today.

**Comment by ParnaRoyChowdhury777** [comment]
> > > Closing as no update
> > 
> > I was occupied with many projects. I can send the PR today.
> 
> Okay, mone kore PR drop kore dishh by EOD. @ParnaRoyChowdhury777 

Haa kore dichhi
