### ISSUE TITLE
[Feature] Adding light/dark theme

### ISSUE THREAD

**Issue by sharmi4590** [pooranjoyb/popShop#353]
### Description

Addin the dark theme and light theme option will enhance the user experience

### Screenshots

![image](https://github.com/user-attachments/assets/f88b5a4e-10aa-4b79-89fe-e971288ea2b6)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @sharmi4590! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @sharmi4590 Nice issue but IDK we can go ahead with this as of now :/
