### ISSUE TITLE
[Feature]: Add a review system

### ISSUE THREAD

**Issue by abckhush** [pooranjoyb/popShop#356]
### Description

This feature should allow customers to leave feedback on products they have purchased, including star ratings and written comments. It will include: 
1. Product pages should display an average rating based on customer reviews.
2. Individual reviews should be shown with the rating, customer comments, and any other relevant details.
3. Ensure that the review system is integrated with the existing backend infrastructure for storing and managing review data efficiently.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @abckhush! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
How do you plan to integrate this feature with the existing system? @abckhush

**Comment by abckhush** [comment]
On clicking the stars for rating, it is not being stored anywhere. Store that and show the average on the post.
Also, reviews can be added and stored in db in a new table with columns: username and review.

**Comment by abckhush** [comment]
@pooranjoyb can you pls assign?

**Comment by abckhush** [comment]
@pooranjoyb ?

**Comment by pooranjoyb** [comment]
> On clicking the stars for rating, it is not being stored anywhere. Store that and show the average on the post. Also, reviews can be added and stored in db in a new table with columns: username and review.

Hey @abckhush i guess iska full system intergrate karna parega fir. Please do the needful and keep me updated.

**Comment by abckhush** [comment]
Yes, I'm willing to do that. But don't you think a whole review system should be of level 3? @pooranjoyb

**Comment by pooranjoyb** [comment]
Will update accordingly after the PR is raised, dw :) @abckhush

**Comment by abckhush** [comment]
@pooranjoyb I have added the Reviews table in supabase and made the UI changes. I am just encountering a few issues, it will be done by tonight or tom morning :)
If you want something else, do let me know.

![image](https://github.com/user-attachments/assets/3c86d1fb-34da-4784-a85f-abe72bdb39a7)
![image](https://github.com/user-attachments/assets/035a67ed-811f-4a65-866a-956516aa00aa)

**Comment by pooranjoyb** [comment]
> @pooranjoyb I have added the Reviews table in supabase and made the UI changes. I am just encountering a few issues, it will be done by tonight or tom morning :) If you want something else, do let me know.

Koi na, take time :)

**Comment by pooranjoyb** [comment]
@abckhush any updates? or should i assign it?

**Comment by abckhush** [comment]
By tonight. For sure.

**Comment by pooranjoyb** [comment]
Oke. @abckhush

**Comment by abckhush** [comment]
@pooranjoyb  Kindly review this pls. And change the level to level3 pls. Its a whole new system with a new database table and all.

**Comment by abckhush** [comment]
@pooranjoyb Kindly see this :)

**Comment by abckhush** [comment]
@pooranjoyb :)
