### ISSUE TITLE
[Feature] Adding hamburger in navbar

### ISSUE THREAD

**Issue by dhairyagothi** [pooranjoyb/popShop#358]
### Description

adding hamburger in mobile view 

### Screenshots

![image](https://github.com/user-attachments/assets/b5340e50-7c0e-4ff8-a34b-78fe4bb56a3f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhairyagothi! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhairyagothi** [comment]
@pooranjoyb please assign me

**Comment by pooranjoyb** [comment]
Well, we already have the Profile Icon to switch to different pages. I guess we dont need this as of now :/
