### ISSUE TITLE
Dark and Light mode 

### ISSUE THREAD

**Issue by pahuja-sahil** [pooranjoyb/popShop#362]
### Description

I would like to add dark and light mode option using a theme toggler in this project as i personally belive it will look good.
Basically an icon in the header will toggle between light and dark theme based on the user preference.
@pooranjoyb kindly assign this issue to me under gssoc 24.
Thank you.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @pahuja-sahil! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pahuja-sahil** [comment]
@pooranjoyb can u assign this issue to me?

**Comment by pooranjoyb** [comment]
Hey this is not planned.
