### ISSUE TITLE
[BUG] Static copyright Year

### ISSUE THREAD

**Issue by Meetjain1** [pooranjoyb/popShop#364]
### Description

Copyright year is not working dynamically It should fetch the current year automatically 

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @Meetjain1! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey you should work on an issue only when you're assigned to work on something. Please take that into notice next time you contribute on any Github repository.

**Comment by pooranjoyb** [comment]
Seems like you're quite new here, so will consider but please take that into consideration. @Meetjain1

**Comment by Meetjain1** [comment]
> Seems like you're quite new here, so will consider but please take that into consideration. @Meetjain1

Sure @pooranjoyb . Thanks for understanding
