### ISSUE TITLE
[Feature] Apply kubernetes your app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [pooranjoyb/popShop#365]
### Description

As your app is dockerize then we can wrap up your app with kubernetes so that your app have many pods which can load balancing your website and also self healf your website and also kubernetes helps in update the code when code is live
It enhance your app performance 

### Screenshots

no screenshot needed

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @agarwalhimanshugaya! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hhaha tbh this is really good and intriguing issue, but as we aren't going for production, we donot plan to execute this as of now :)
You can go for other issues @agarwalhimanshugaya
