### ISSUE TITLE
[BUG] add to cart error

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#367]
### Description

when i click on add to cart then display error 

### Screenshots

![image](https://github.com/user-attachments/assets/ac3ef905-0523-4309-b4c3-027d1128da6d)

in console show this err when click on add to cart

![image](https://github.com/user-attachments/assets/204be3b5-51a3-4c99-9bba-30526d090e88)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,please assign this issue

**Comment by pooranjoyb** [comment]
Yup fix this :/ @Varsani2520

**Comment by Varsani2520** [comment]
thank you for assign me @pooranjoyb
