### ISSUE TITLE
[Feature] product caard not show same size and also image is not show in some cards

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#369]
### Description

@pooranjoyb 

there are missing images in products tab and also card size got changed 

### Screenshots

![image](https://github.com/user-attachments/assets/2bbed5c3-5ce1-4ff0-a2fe-bbee61898ce5)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,assign me

**Comment by pooranjoyb** [comment]
Yes fix this :/ @Varsani2520

**Comment by Varsani2520** [comment]
ok @pooranjoyb
