### ISSUE TITLE
[BUG] Missing Website icon on tab 

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#370]
### Description

@pooranjoyb 

we can add popshop logo in tab icon

### Screenshots

![image](https://github.com/user-attachments/assets/c7b69944-128a-472c-a319-6b75496dd46e)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well this is actually there but sometime doesn't show up due to network error.
