### ISSUE TITLE
[BUG] :in profile display all the details about user

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#373]
### Description

in user profile we can add some features like display all the order,

and also we can add user have option to like the product and liked product display in profile 
so user easily purchase the liked product

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
What needs to be done? @Varsani2520
