### ISSUE TITLE
[BUG] in profile mobile edit option

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#374]
### Description

in mobile number edit option :user able to allow only enter digits and also limit upto 10 

so validation like mobile number
![image](https://github.com/user-attachments/assets/e760939c-2dae-4977-9a1d-1b9824ae947b)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>
