### ISSUE TITLE
[BUG] Aling Card 

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#376]
### Description

@pooranjoyb 

we can make same size of cards

### Screenshots

![image](https://github.com/user-attachments/assets/747c6c09-621b-4861-b8c6-b9d81ee13594)

![image](https://github.com/user-attachments/assets/0bbeef77-dfd9-40c9-9772-85b35a6425a6)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>
