### ISSUE TITLE
[Feature] Store Contact information in Database

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#378]
### Description

@pooranjoyb 

we can store contact information in supabase 

### Screenshots

![image](https://github.com/user-attachments/assets/4e70ba22-8e1e-4ed1-8f38-9cbfd4443a79)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hey @dhruv8433 iska toh direct mail pe jaata hai :)
We already fixed that. I mean bss `.env` me added nahi hai, baaki this works!
