### ISSUE TITLE
[Feature] we can add liked icon in products

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#379]
### Description

we can add that then user able to liked their products and also able to see their liked product in their profile  

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Varsani2520** [comment]
@pooranjoyb ,please assign me

**Comment by pooranjoyb** [comment]
How is it different from Cart?

**Comment by Varsani2520** [comment]
@pooranjoyb ,something like wishlists

we dont want to add items into cart and we will purchase later on

**Comment by Varsani2520** [comment]
like flipkart:
![image](https://github.com/user-attachments/assets/d5fa2072-db97-48bc-ad5c-301c4d0227d2)

**Comment by pooranjoyb** [comment]
okay :)

**Comment by Varsani2520** [comment]
Can you please assign me

**Comment by Varsani2520** [comment]
@pooranjoyb ,do you interested in this Issue ?

**Comment by pooranjoyb** [comment]
Yes go for it! @Varsani2520

**Comment by Varsani2520** [comment]
@pooranjoyb,assign me so i can start the issue
