### ISSUE TITLE
Regarding Website animations

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [pooranjoyb/popShop#38]
Hi i am Ram #gssoc24
i want to add some cool scrolling animations in your website
tech stack to be used
-aos.js
-tilt.js
@pooranjoyb

**Comment by pooranjoyb** [comment]
Hii @RamakrushnaBiswal 

List down the `framer-motion` animations you wanna add :)

**Comment by RamakrushnaBiswal** [comment]
@pooranjoyb yes sir i can

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @RamakrushnaBiswal

**Comment by pooranjoyb** [comment]
@dev04sa Can you work on this?

**Comment by dev04sa** [comment]
> @dev04sa Can you work on this? Also are you using `Framer Motion` ?

Yes I can work on this , with Framer motion.

**Comment by pooranjoyb** [comment]
Go ahead :) 🚀 @dev04sa

**Comment by pooranjoyb** [comment]
Update @dev04sa

**Comment by dev04sa** [comment]
@pooranjoyb changes done.
