### ISSUE TITLE
Make the FAQ open on hover to improve experience

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#380]
### Description

The FAQ answer should open on hovering the question 

### Screenshots

![image](https://github.com/user-attachments/assets/3278202a-2746-48fd-ab65-558e42b9eeb3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Na bhai, we should click it to open it up :/
