### ISSUE TITLE
Make the floating navbar for Mobile screen also to keep it on the top

### ISSUE THREAD

**Issue by Utsavladia** [pooranjoyb/popShop#381]
### Description

The navbar should be on the top to access it from anywhere

### Screenshots

![image](https://github.com/user-attachments/assets/ac3d12e4-7000-4e1b-aaae-1d206a8dd98b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @Utsavladia! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well, I think this is not needed for now :/
