### ISSUE TITLE
Adding Testimonials

### ISSUE THREAD

**Issue by sharmi4590** [pooranjoyb/popShop#383]
Adding testimonials for the shop would enhance the user experience . These are my previous works.
![Screenshot (398)](https://github.com/user-attachments/assets/f6a89869-d683-4283-8e87-8063b0e595e6)
![Screenshot (399)](https://github.com/user-attachments/assets/85199d1e-32c9-4356-9e5e-15075f3b82f2)
![Screenshot (400)](https://github.com/user-attachments/assets/f2ad15a6-2e31-4480-bd80-1538df827dd6)
![Screenshot (401)](https://github.com/user-attachments/assets/27da5e09-18f9-4cab-bad5-e61da7067f78)

**Comment by pooranjoyb** [comment]
Congratulations, @sharmi4590! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Hii @sharmi4590 we aren't working on a real life product so, IG this ain't necessary as of now :)
