### ISSUE TITLE
[Feature] we can add rating value in supabase

### ISSUE THREAD

**Issue by Varsani2520** [pooranjoyb/popShop#384]
### Description

we can add rating value in supabase and display in profile favourite card so look like cool :

### Screenshots

![image](https://github.com/user-attachments/assets/fcaa4a4e-1164-49ba-8411-9149910ff5e1)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Varsani2520** [comment]
@pooranjoyb ,assign me

**Comment by pooranjoyb** [comment]
Congratulations, @Varsani2520! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I gues this is already existing :) @Varsani2520

**Comment by Varsani2520** [comment]
@pooranjoyb ,when user give rating then that value not store in supabase  see carefully :
![image](https://github.com/user-attachments/assets/40bb15e0-da8b-4441-8c95-8682058701ac)
 
i think this rating is dummy not happen anything :![image](https://github.com/user-attachments/assets/fcaa4a4e-1164-49ba-8411-9149910ff5e1)
I want to display overall rating in product detailed page like flipkart and amezon have     
![image](https://github.com/user-attachments/assets/93e27817-04be-472b-859d-9909ea3f066c)

**Comment by pooranjoyb** [comment]
Ok do it then @Varsani2520
