### ISSUE TITLE
[BUG] Footer section ui

### ISSUE THREAD

**Issue by Sourabh782** [pooranjoyb/popShop#385]
### Description

The footer section image looks out of sync, i wanted to work on the footer to make it more apealing

### Screenshots

![Screenshot 2024-08-04 145033](https://github.com/user-attachments/assets/297b68ff-4bf1-4f97-b417-a0c27dfd3d66)

### What browser are you seeing the problem on?

Chrome

**Comment by pooranjoyb** [comment]
Congratulations, @Sourabh782! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Sourabh782** [comment]
Hello @pooranjoyb, does it mean i can work on this issue?

**Comment by pooranjoyb** [comment]
Haa fix kardo :)  @Sourabh782
