### ISSUE TITLE
[Feature]  we can add reviews section in product and store in supabase

### ISSUE THREAD

**Issue by dhruv8433** [pooranjoyb/popShop#386]
### Description

@pooranjoyb 

we can add review section and store it in supabase with product it 

### Screenshots

![image](https://github.com/user-attachments/assets/cc1c8051-cd0a-4ecc-a02b-ee5b0f9f1b18)

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @dhruv8433! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by dhruv8433** [comment]
@pooranjoyb 

we can add beautiful review form where user can add their review about particular product 
based on product id

**Comment by pooranjoyb** [comment]
Existing issue #356
