### ISSUE TITLE
[BUG] Hamburger icon needs to be replaced with close icon 

### ISSUE THREAD

**Issue by kapilG0** [pooranjoyb/popShop#390]
### Screenshots

![Screenshot_20240807_181858](https://github.com/user-attachments/assets/4292f6cf-e3ea-4734-9d5a-dcd77ab63aa1)

### What browser are you seeing the problem on?

Chrome

**Comment by kapilG0** [comment]
Hello @pooranjoyb please assign this issue to me under gssoc 24

**Comment by pooranjoyb** [comment]
Yes fix this :) @kapilG0

**Comment by kapilG0** [comment]
Hello @pooranjoyb i raised pr https://github.com/pooranjoyb/popShop/pull/392. please check
