### ISSUE TITLE
Providing a feedback option

### ISSUE THREAD

**Issue by mahek0620** [pooranjoyb/popShop#391]
### Description

The Feedback option aims to collect user insights, suggestions, and issues related to the project, enabling continuous improvement and fostering user engagement.

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @mahek0620! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Well I don't think we need this at this moment :p @mahek0620
