### ISSUE TITLE
[OTHER]how to add description and review tab under product

### ISSUE THREAD

**Issue by wanghaisheng** [pooranjoyb/popShop#397]
### What would you like to share or ask?

https://pop-shop-github.vercel.app/home/shop/product
there is alway design in collapse tab or side by side tab which can describe the detail about product, such as review,shipping and etc

### Checklist

- [X] I have checked the existing [issues](https://github.com/pooranjoyb/popShop/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/pooranjoyb/popShop/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by pooranjoyb** [comment]
Congratulations, @wanghaisheng! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go for it @wanghaisheng
