### ISSUE TITLE
UI-Adding Rating to Product Page

### ISSUE THREAD

**Issue by Disha-Hati** [pooranjoyb/popShop#4]
We add an UI feature of Star rating in the Products page.
I'm GSSOC'24 Contributor. Can you please assign this issue to me?

**Comment by pooranjoyb** [comment]
Hey @Disha-Hati one issue at a time :)

**Comment by Tomkndn** [comment]
Hey, I would like to work on this project, Can you please assign me this issue.

**Comment by pooranjoyb** [comment]
> Hey, I would like to work on this project, Can you please assign me this issue.
> 
> But my question is the rating will be provided form the backend i.e firebase or for now it should be hard coded.

Absolutely, go ahead. Use the component from Daisy UI. Hard code it as of now. Later we'll integrate that.

**Comment by Manaswini123456** [comment]
Can you please assign the issue to me, I would like to collaborate and provide my insights and solutions.

**Comment by pooranjoyb** [comment]
Update @Tomkndn ?

**Comment by Tomkndn** [comment]
just want to confirm the update this is fine or any other modification
![image](https://github.com/pooranjoyb/popShop/assets/105445488/48558c0f-6707-4284-851d-d23ffbf9c769)

**Comment by pooranjoyb** [comment]
Works! @Tomkndn
