### ISSUE TITLE
Regarding Styling & Alignment 

### ISSUE THREAD

**Issue by sachin0986** [pooranjoyb/popShop#42]
Hi **@pooranjoyb** I found some issues in styling and alignment

### Description of Issue 1
> When I am clicking on cart section then the popup window is hiding the text.

**Reproduce Issue**
Open in Mobile view to view issue.

**Screenshot**

<img width="469" alt="Screenshot 2024-05-12 at 1 19 29 PM" src="https://github.com/pooranjoyb/popShop/assets/106465241/89df4593-fd65-424e-ad4a-02118eb1e61c">

### Description of Issue 2
> The alignment of Footer is not in centre.

**Reproduce Issue**
Open in Mobile view to view issue.

**Screenshot**
<img width="535" alt="Screenshot 2024-05-12 at 1 23 23 PM" src="https://github.com/pooranjoyb/popShop/assets/106465241/e4f0e86e-75d8-4de2-8035-55b36578367c">

### Description of Issue 3

>When I am clicking on Profile section then the popup window is hiding the search bar.
**Reproduce Issue**
Open in Mobile view to view issue.

**Screenshot**
<img width="469" alt="Screenshot 2024-05-12 at 1 20 19 PM" src="https://github.com/pooranjoyb/popShop/assets/106465241/071abc12-f00a-47f7-9a2c-c6255028d8f1">

I am a GSSOC'24 contributor. Can you please assign this issue to me? @pooranjoyb
Please also mention GSSOC and level labels.
thank you.

**Comment by pooranjoyb** [comment]
Most of the things aren't responsive as of now. It's been worked upon in #20 Will update you soon regarding it! @sachin0986

**Comment by sachin0986** [comment]
Alright, waiting to get updated from your side 😀.

**Comment by pooranjoyb** [comment]
Hey @sachin0986 Can you co-author commits on #54 ?
