### ISSUE TITLE
Correction in routes

### ISSUE THREAD

**Issue by BHS-Harish** [pooranjoyb/popShop#43]
Hello @pooranjoyb 

I have go through your website entirely
The pages are not loading with corresponding route in url bar. It may confusing the users as well as other developers.

I would like to work on the issue.
Please assign the issue to me

Thanks in advance

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb 
> 
> I have go through your website entirely
> The pages are not loading with corresponding route in url bar. It may confusing the users as well as other developers.
> 
> I would like to work on the issue.
> Please assign the issue to me
> 
> Thanks in advance

Hii @BHS-Harish Welcome to Popshop!
Could you elaborate the issue you've mentioned.?

**Comment by BHS-Harish** [comment]
The Homepage loaded in /home instead of /.
The login page loaded in / instead of /login or /auth
product and cart pages as well

These routes are not meaningful

**Comment by BHS-Harish** [comment]
## Proposed routes are :
- / - Home page
- /auth - Login/Signup page
- / shop - Shop page
- /product -  Product page
- /cart - Cart page

**Comment by BHS-Harish** [comment]
Hello @pooranjoyb  I mentioned the issue elaborately above.

Please assign the issue to me

**Comment by pooranjoyb** [comment]
Okay so as of now we aren't actually planning a separate landing page and a dashboard page for the user. I mean the landing itself is the `Home` of the user.
We make / as index coz we'll setup Redux, and once that's done, user will auto-redirect to Home, without login. Do lmk if you have any other doubts.

**Comment by pooranjoyb** [comment]
Okay so as of now we aren't actually planning a separate landing page and a dashboard page for the user. I mean the landing itself is the `Home` of the user.
We make / as index coz we'll setup Redux, and once that's done, user will auto-redirect to Home, without login. Do lmk if you have any other doubts.

**Comment by BHS-Harish** [comment]
No doubts @pooranjoyb 

Thanks
