### ISSUE TITLE
Issue in Cart functionality

### ISSUE THREAD

**Issue by sachin0986** [pooranjoyb/popShop#46]
### Description
When I am increasing the quantity of one item than it updates quantity of other items also, and the subtotal is also not updating.

### Reproduce Issue
Open **Cart Section** then try to increase or decrease the quantity of items.

### ScreenRecording
https://github.com/pooranjoyb/popShop/assets/106465241/c11d93a9-88a8-4a6a-bbd6-06becc48cb3a

I am a GSSOC'24 contributor. Can you please assign this issue to me? @pooranjoyb
Please also mention GSSOC and level labels.
thank you.

**Comment by pooranjoyb** [comment]
Hii @sachin0986 check #7
Closing this as duplicate & will assign you #7 if there's no update by tomorrow :)

**Comment by sachin0986** [comment]
Alright.
