### ISSUE TITLE
The login and signup by google is not functioning  

### ISSUE THREAD

**Issue by AnitSarkar123** [pooranjoyb/popShop#48]
please assign me under GSSoC'24

**Comment by pooranjoyb** [comment]
We'll work on this after the React-Redux is setup for the project :)

**Comment by AnitSarkar123** [comment]
ok i will wait 
please infromme

**Comment by MdSaifAliMolla** [comment]
> We'll work on this after the React-Redux is setup for the project :)

how to signup ?email auth is also not working.
