### ISSUE TITLE
Homepage is missing an interactive header with a logo

### ISSUE THREAD

**Issue by pranjali-srvstv** [pooranjoyb/popShop#5]
The Home Page looks a bit simple, I can make it more interactive along with a logo. I'm GSSOC'24 contributor, so can you please assign this issue to me?

**Comment by pooranjoyb** [comment]
> The Home Page looks a bit simple, I can make it more interactive along with a logo. I'm GSSOC'24 contributor, so can you please assign this issue to me?

Hii @pranjali-srvstv as of now we are planning to fix the minor bugs and ui issues in the webpage. I appreciate your request but this issue will be worked upon at a later stage in the event. 

Mentors will create this issue soon ;) keep a track on the repo for the updates. Meanwhile you can create other issues. Happy coding :)
