### ISSUE TITLE
Animation in HomePage

### ISSUE THREAD

**Issue by dev04sa** [pooranjoyb/popShop#53]
@pooranjoyb ,By adding animation at Homepage we can enhance User-experience.
Kindly asiign this issue to me.
Here is the sample video provided for , how animation look like:

https://github.com/pooranjoyb/popShop/assets/129666293/bf1b1e47-887c-4f1b-a04f-01c5e89b55d7

**Comment by pooranjoyb** [comment]
Duplicate, Assigning you #38
