### ISSUE TITLE
[FEATURE] Add 'Buy Now' button and 'Add to Cart' icon on the Products Page

### ISSUE THREAD

**Issue by yashmandi** [pooranjoyb/popShop#55]
In the below Products Page, there should be a 'Buy Now' Button and 'Add to cart' icon to each product, similar to modern websites.
Customer finds this feature effecient as going into the specific product page and then adding it to cart / buying it, is a bit lengthy process. 
I have been working on similar project and can get this done ASAP. 
I would like to contribute to this task under GSSOC '24

![Screenshot (195)](https://github.com/pooranjoyb/popShop/assets/132436131/22f75bdb-6573-4e98-b9b2-b0b05c33876a)

**Comment by pooranjoyb** [comment]
I guess this already exists :)

![image](https://github.com/pooranjoyb/popShop/assets/90945182/d612ee7c-df63-487a-9d70-0287f51de923)

Do lmk if you meant something different. @yashmandi

**Comment by yashmandi** [comment]
I mean something like this. in the products page, each product should have a button / icon to add to wishlist or cart or buy now.
currently, we can only see the buttons once the user enters the specific product page, the one you've attached the screenshot of above. 
![demo](https://github.com/pooranjoyb/popShop/assets/132436131/7c35d819-667e-4782-93ef-3c667ab237c1)

**Comment by pooranjoyb** [comment]
Okay do it :)
Maintain the theme and use the `Button` component that's already available. @yashmandi

**Comment by pooranjoyb** [comment]
Assigned @yashmandi 🚀

**Comment by Amitooo1** [comment]
Hey @Mahitej28 ! i would like to work on this issue. I'm familiar with popshop codebase as i raised a PR today morning. so can you please assign me?

**Comment by pooranjoyb** [comment]
Go ahead @Amitooo1 🚀

**Comment by Amitooo1** [comment]
Thanks @pooranjoyb i'll solve this issue soon
