### ISSUE TITLE
[FEATURE] Add Notification Toasts when Products are Added or Removed to Cart

### ISSUE THREAD

**Issue by yashmandi** [pooranjoyb/popShop#57]
When customer adds a product to cart, a toast should appear at the right top area that 'Product has been added' and also when the product is removed from cart too. This gives a sense of confirmation to customers that the product has been successfully added/removed.
Would request you to assign this task to me under GSSOC '24
We can do it in below page: 
![Screenshot (196)](https://github.com/pooranjoyb/popShop/assets/132436131/6e7f2796-403a-49b2-b6a7-ae07a7489e04)

**Comment by pooranjoyb** [comment]
One issue at a time buddy :) 👍🏼  @yashmandi

**Comment by yashmandi** [comment]
I can work on this issue first for now, and later on issue #56 
Request you to assign this issue to me.

**Comment by pooranjoyb** [comment]
As of now, no need to manage the State, just show the `Toast` on click of Add to Cart. @yashmandi
