### ISSUE TITLE
Authentication State Needed to be persisted.

### ISSUE THREAD

**Issue by NIveX2169** [pooranjoyb/popShop#63]
As when we are logged in and we are going through one routes to another it works fine but when we manually type in different routes browser again send the request to backend(react restart) and then redux is getting reset. This is what i observed if something other than this is happening then do tell me and also assign me this task....
Thank you

**Comment by pooranjoyb** [comment]
### Tasks : 

- [ ] Fix the `Signup Auth` redirection Bug. 
- [ ] Persist `User-Auth` state


All the best! @NIveX2169
