### ISSUE TITLE
Animated loading page 

### ISSUE THREAD

**Issue by Priyapandeyyy** [pooranjoyb/popShop#68]
I want to add an animated loading page something like this at the beginning of the page.

![loader](https://github.com/pooranjoyb/popShop/assets/132647631/6771aa11-3774-4e38-a0d7-27f43286a8f8)

**Comment by pooranjoyb** [comment]
Congratulations, @Priyapandeyyy! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go Ahead! @Priyapandeyyy 🚀

**Comment by Mayur-666** [comment]
@pooranjoyb  Please assign me this issue, I have its code ready.

![Screenshot (552)](https://github.com/pooranjoyb/popShop/assets/118804110/e972a032-fe16-4b3d-b055-1386f783b80b)

**Comment by pooranjoyb** [comment]
Go for it @Mayur-666 🚀

**Comment by Mayur-666** [comment]
Hello @pooranjoyb, I have added Loader.tsx in components folder, i am not sure about the places where we can use it.

**Comment by Mayur-666** [comment]
Tell me should i push only the loader files i made, or the locations where i can add the loader.

**Comment by pooranjoyb** [comment]
Use these color theme : 
- `#06D6A0`
- `#EF476F`
- `#FFD166`
- `#118AB2`
- `#073B4C`

@Mayur-666

**Comment by Mayur-666** [comment]
Sure! @pooranjoyb  and what about the above issue.

**Comment by Mayur-666** [comment]
Sorry to say, i was only able to add loader file, i don't know about SUPABASE so didn't able to test and set it up. 
You can pin a new issue regarding the adding of loading effects. 

I can only contribute to the loader and animation. Hope you understand @pooranjoyb. 
So should i create a PR or ??

**Comment by pooranjoyb** [comment]
Yup go for it! @Mayur-666
