### ISSUE TITLE
Feat: Implement Animations and Enhance User Experience.

### ISSUE THREAD

**Issue by Mujtabaa07** [pooranjoyb/popShop#69]
Best Effects on Buttons ,
Transition Effects while scrolling,
hover and animations ,
Please assign me this issuse @pooranjoyb 
i'll be happy to resolve it asap.

**Comment by pooranjoyb** [comment]
Congratulations, @Mujtabaa07! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mujtabaa07** [comment]
please label it

**Comment by pooranjoyb** [comment]
Go ahead! @Mujtabaa07

**Comment by pooranjoyb** [comment]
No update, hence closing :/

**Comment by Mujtabaa07** [comment]
I'm Sorry for inconvenience @pooranjoyb , please reopen it , i'll fix it asap as mentioned

**Comment by pooranjoyb** [comment]
Bruh it was last week's. Anyways as you say so, take a day, gimme a prototype PR by tom EOD. @Mujtabaa07
