### ISSUE TITLE
Cart Functionalities- + and - 

### ISSUE THREAD

**Issue by Disha-Hati** [pooranjoyb/popShop#7]
On Clicking + it increases
On Clicking - the count decreases
It should happen separately for each item,
Solution:  This we can achieve by passing the product name(hard-coded) as props.

Can you please assign this issue to me?
![image](https://github.com/pooranjoyb/popShop/assets/70029959/37c4b7f0-69db-4b6d-a108-09ad806c9a12)

**Comment by pooranjoyb** [comment]
Hii @Disha-Hati this is similar to #1 right.?

**Comment by Disha-Hati** [comment]
> Hii @Disha-Hati this is similar to #1 right.?

Yes, but in that I just removed arrows(basically replaced input with div and state variable)
Right now if I click on + , all the items-count increases, because there is no segregation of Components

Solution: This whole ADD SUB component can be extracted and put into a separate component, (enhancing Single Responsibility principle and Code readability and reusability ), and the items can be passed as props. 
It can be added to Products Page as well.
![image](https://github.com/pooranjoyb/popShop/assets/70029959/3676f1e0-0f7c-460e-9f0e-5693ce1f7218)

**Comment by pooranjoyb** [comment]
Yes This is a bug, Fix it! @Disha-Hati

**Comment by Disha-Hati** [comment]
Sure, Thank You

**Comment by Disha-Hati** [comment]
It's done.
https://github.com/pooranjoyb/popShop/pull/61
Can you please merge my PR?

**Comment by Disha-Hati** [comment]
https://github.com/pooranjoyb/popShop/pull/62
Can you please merge my PR?
