### ISSUE TITLE
[FEATURE] Add 'Favourites' Button and Page

### ISSUE THREAD

**Issue by yashmandi** [pooranjoyb/popShop#71]
Creating 'Favourites' Page will enhance user experience where users can add the products to their favourites just in one click. Which can later on moved to cart as oer user's choice.

Would like to work on this issue under GSSOC '24

**Comment by pooranjoyb** [comment]
Congratulations, @yashmandi! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Umm, kinda good idea. Will discuss with the mentors and will get back to you.

**Comment by Niharika0104** [comment]
@pooranjoyb this issue was created 17 h back and I created it 4 days back.I.would like to work on this.

**Comment by pooranjoyb** [comment]
@Niharika0104 & @yashmandi can work on #11 together.
We'll let you know further decisions for this page :)
Happy Coding, keep looking for more bugs and fixes.
