### ISSUE TITLE
[Bug] : Cart Page Quantity

### ISSUE THREAD

**Issue by sivaprasath2004** [pooranjoyb/popShop#72]
- If the `Cart` Pages `Quatity ` can be added that is selelcted for the all product `quantity` also can added.
- If the cart option to solve for the `.some` , `.includes` and `.filter` method to solve the issue..
- please assign me i will ready to make fix the issues..

[Screencast from 2024-05-14 13-18-40.webm](https://github.com/pooranjoyb/popShop/assets/121082414/de30c1bc-d2e8-4b32-8c5d-aaa286721c0e)

**Comment by pooranjoyb** [comment]
Congratulations, @sivaprasath2004! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go for it! @sivaprasath2004
