### ISSUE TITLE
Bug when user is logged in and if he goes back login/sign up page appears

### ISSUE THREAD

**Issue by NIveX2169** [pooranjoyb/popShop#76]
we need to use conditional routing if users once logged in cannot go to login in  page

**Comment by pooranjoyb** [comment]
Congratulations, @NIveX2169! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Go for it! @NIveX2169
