### ISSUE TITLE
[Feat] : Profile Page 

### ISSUE THREAD

**Issue by Sid-80** [pooranjoyb/popShop#77]
## Describe

There is no profile page or modal which gives user info.

Please assign me this issue under GSSOC'24

**Comment by pooranjoyb** [comment]
Congratulations, @Sid-80! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Yup go for it! Create a Profile Page. Follow the directory structure for `pages`

It should have 
- Default Avatar of User
- Username
- First Name
- Last Name
- Gender
- Account Creation Date
- Address
- Phone Number 

#### Use `react-icons` and `Daisy UI` theme. @Sid-80

**Comment by Sid-80** [comment]
Sure!

**Comment by Sid-80** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/101277141/cbf5b76b-7ee6-4b6d-8292-a2b9b607a817)

We are storing only this much attribute as input should I make others as blank field ?

**Comment by Sid-80** [comment]
Can I use Username to retrieve data?

**Comment by pooranjoyb** [comment]
> Can I use Username to retrieve data?

No as of now just work with the UI. We'll do integration later. As we need to update the `schema` as well as `Signup Form` as well as `Supabase Table` @Sid-80

**Comment by pooranjoyb** [comment]
Follow this UI

- Use colors based on PopShop theme
- change the user avatar to a static image
- `Contact` button should be `Explore Products` that should redirect to `/home/shop`
- Profile section should contain all the user's information in 2 columns
- Don't forget to create the route for it in `browserRoutes.tsx`

@Sid-80 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/10a54085-5f51-4a43-a4aa-5b48111eea42)

![image](https://github.com/pooranjoyb/popShop/assets/90945182/093901f6-3cdc-4327-a9e2-3829c2aeed12)

**Comment by pooranjoyb** [comment]
Nada, it looks cool! Use some light, aesthetic sorta background. Nice work tho! @Sid-80 
Use `Head` component for the Profile and `name` under the dp.
Also `Profile` Heading should be on top.
