### ISSUE TITLE
Go to Login page UI design enhancement

### ISSUE THREAD

**Issue by manpreet244** [pooranjoyb/popShop#78]
![image](https://github.com/pooranjoyb/popShop/assets/63246393/15a83b22-b10e-4773-b784-cef6baef46d8)
this page has not designed yet

**Comment by pooranjoyb** [comment]
Congratulations, @manpreet244! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by manpreet244** [comment]
wanna work on this issue , please , assign it to me under gssoc

**Comment by pooranjoyb** [comment]
go for it! Use the `Navbar` & `Footer` and show the text `Login to Continue` with the `Head` component

**Comment by manpreet244** [comment]
ok got it , will done it by tommorow

**Comment by manpreet244** [comment]
@pooranjoyb  why there is nothing shown up , when i run npm run dev
![image](https://github.com/pooranjoyb/popShop/assets/63246393/e9436dde-808c-4ced-bcd7-77eed15c6816)

**Comment by pooranjoyb** [comment]
did you follow `contributing guidelines`?

**Comment by pooranjoyb** [comment]
Closing this as decision changed.
