### ISSUE TITLE
Google Oauth for authentication

### ISSUE THREAD

**Issue by NIveX2169** [pooranjoyb/popShop#79]
Using google oauth we will authenticate our login/signup form .

For that i need to have access of database. so for that kindly add me to the  project .

My email is shashanksinghnegi12@gmail.com.

**Comment by pooranjoyb** [comment]
Congratulations, @NIveX2169! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
![image](https://github.com/pooranjoyb/popShop/assets/90945182/17f3512d-8eac-48c8-b88e-2cb1f89e4a4b)

Added. Please check :) @NIveX2169

**Comment by NIveX2169** [comment]
Yes i have received it.

**Comment by NIveX2169** [comment]
> update @NIveX2169 ?

Sorry I was busy ... I will do it by this Sunday is it fine to you?

**Comment by pooranjoyb** [comment]
No issues, kinda important issue tho. Make sure to drop the PR by sunday EOD :)

**Comment by pooranjoyb** [comment]
What's the update @NIveX2169 ? Been 2 weeks now :/

**Comment by pooranjoyb** [comment]
Hii @NIveX2169 could you drop the PR by EOD?

**Comment by pooranjoyb** [comment]
One issue at a time @harini-1597 :/

**Comment by masterboy376** [comment]
hello @pooranjoyb, I could work on this is the mean time.

**Comment by NIveX2169** [comment]
> hello @pooranjoyb, I could work on this is the mean time.
> email: masterboy376@gmail.com

Yes @pooranjoyb  let him do ...

**Comment by Tomkndn** [comment]
@pooranjoyb If no one is currently working, then I am interested to this issue.
Kindly assign to me.

**Comment by masterboy376** [comment]
Hello @pooranjoyb I need to access database for this. Could you please add me to the supabase project.
email: masterboy376@gmmail.com

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb I need to access database for this. Could you please add me to the supabase project. email: [masterboy376@gmail.com](mailto:masterboy376@gmail.com)

Invite sent. Please check mail.

**Comment by masterboy376** [comment]
Hello @pooranjoyb, I have decided to use google cloud to enable google auth screen, and then integrate it to supabase. So does this project already have an existing google cloud project.

**Comment by NIveX2169** [comment]
> Hello @pooranjoyb, I have decided to use google cloud to enable google auth screen, and then integrate it to supabase. So does this project already have an existing google cloud project.
> 

Yes I have integrated that you can simply remove that ....go to Google console add up details ...and then remove details from supabase ....

**Comment by NIveX2169** [comment]
You are going to use jwt for authentication right!!
