### ISSUE TITLE
Client Side Validation 

### ISSUE THREAD

**Issue by NIveX2169** [pooranjoyb/popShop#80]
when signing up we don't have strict checks . Sending unsanitised data would bring vulnerabilities to the system. Though Client side validation would not be effect as server side santisation.but still for now we can do cllient side validation in form .

**Comment by pooranjoyb** [comment]
Congratulations, @NIveX2169! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
I guess client side validation is already done in `utils/schema.ts` @NIveX2169

**Comment by NIveX2169** [comment]
yes it is fine
