### ISSUE TITLE
Refining Protected Routes.

### ISSUE THREAD

**Issue by Mayur-666** [pooranjoyb/popShop#82]
Currently if someone access any route which requires login, it is showing a button "Go to login Page" which is not that good.
Here is a snapshot: -
![Screenshot (549)](https://github.com/pooranjoyb/popShop/assets/118804110/fbaa7ecc-f927-4b8c-8a83-c7eff8c03c5b)

See it is not looking food on this fashion website.
I want to re-code protected routes file , so that if anyone tries to access it will be redirected to login page automatically.
This will not only work well, but also enhances user experience.

**Comment by pooranjoyb** [comment]
Congratulations, @Mayur-666! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mayur-666** [comment]
@pooranjoyb  Please look forward to it and assign me this issue.

**Comment by pooranjoyb** [comment]
> @pooranjoyb  Please look forward to it and assign me this issue.

Hii @Mayur-666 #78 already exists!
Looking forward for more valuable contributions. 
Happy coding. ✨️

**Comment by Mayur-666** [comment]
@pooranjoyb Actually, the #78  is to enhance the ui of that page, But i don't want that page,
As you have already implemented RTK, i want it to redirect to the login page automatically without any intermediate page.

**Comment by Mayur-666** [comment]
Please reconsider it.

**Comment by pooranjoyb** [comment]
@Mahitej28 do lmk your thoughts on this.

**Comment by Mahitej28** [comment]
Ig this is a more better option, in most of the formal websites users get redirected to the login page.

> @Mahitej28 do lmk your thoughts on this.

**Comment by Mayur-666** [comment]
@pooranjoyb  So what do you think ??

**Comment by pooranjoyb** [comment]
Yup lets do this then. @Mayur-666

**Comment by pooranjoyb** [comment]
yup go ahead with this. Raise the PR by EOD. @Mayur-666
