### ISSUE TITLE
BUG:show add to cart notification but quantity is zero 

### ISSUE THREAD

**Issue by panam1916** [pooranjoyb/popShop#88]
![Uploading Issue.png…]()
![Issuecart](https://github.com/pooranjoyb/popShop/assets/92396633/604775ed-1572-40c9-9e98-e3775c9de9a3)
In this i can improve it by first select size and quantity and then it show add to cart solution otherwise it show notification for not selected (Or set Quantity to by default 1 and also default select size because without this you cant set into cart )

**Comment by pooranjoyb** [comment]
Congratulations, @panam1916! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by panam1916** [comment]
We can do one thing by efault we start quantity feature with 1

**Comment by pooranjoyb** [comment]
This will be a functional issue and will be worked upon later. @panam1916
