### ISSUE TITLE
Add email verification for signup

### ISSUE THREAD

**Issue by linhphan03** [pooranjoyb/popShop#89]
- Currently, user can enter whatever email (even non-existent ones) to sign up. We can prevent people spamming by verifying email

@pooranjoyb please assign it to me under GSSoC

**Comment by pooranjoyb** [comment]
Congratulations, @linhphan03! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Mahitej28** [comment]
@linhphan03 check issue no #79
