### ISSUE TITLE
Search functionality is not working

### ISSUE THREAD

**Issue by Niharika0104** [pooranjoyb/popShop#9]
The search functionality is not working as expected.

### Steps to Reproduce

1. Go to the products page.
2. Enter the product name that you want to search.
3. Click on search button.
4. Observe the unexpected behavior i.e no products are being shown.

### Expected Behavior

After performing a search, the system should display relevant search results based on the entered query.

### Actual Behavior

No products are being shown

**Comment by pooranjoyb** [comment]
Cool go for it! @Niharika0104 🚀 

Take the pull from `dev` branch before working onto anything. And don't forget to raise the PR to `dev`

**Comment by Niharika0104** [comment]
Sure

**Comment by pooranjoyb** [comment]
Update?

**Comment by Niharika0104** [comment]
I will push the code today
