### ISSUE TITLE
Add Favicon.

### ISSUE THREAD

**Issue by SwanandD121** [pooranjoyb/popShop#92]
**Problem**
The website lacks a favicon, which diminishes its professional appearance and branding consistency. A favicon is a small but essential element that appears in the browser tab and bookmarks, helping users quickly identify and navigate to the website.

**Solution**
Adding the favicon which will be the shoe image from the home banner component.

Please assign me this issue under GSSoC'24.

**Comment by pooranjoyb** [comment]
Congratulations, @SwanandD121! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Duplicate #23
