### ISSUE TITLE
[BUG] : redux-persist

### ISSUE THREAD

**Issue by Sid-80** [pooranjoyb/popShop#93]
## Describe
When user logs in and if he refreshes the page or just change the window the state gets back to the initial state.

## Solution
Redux persist is implementation is missing. Gets resolved after implementation of redux-persist

@pooranjoyb Please assign me this issue under GSSOC24

**Comment by pooranjoyb** [comment]
Congratulations, @Sid-80! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
Check `dev` its already there.
