### ISSUE TITLE
BUG: Irragular height of image in "new collections" section

### ISSUE THREAD

**Issue by Amitooo1** [pooranjoyb/popShop#95]
![image](https://github.com/pooranjoyb/popShop/assets/108569153/f800209d-d1b8-4a43-9da1-ff6d5a72c5fe)

as you can see in above image, height of second image is more than the combined 3rd and 4th image which looks odd visually.
You can see more clearly here:
![image](https://github.com/pooranjoyb/popShop/assets/108569153/7a877a0a-ed38-4276-9e85-19bd4450975a)

I would like to work on this under gssoc.

**Comment by pooranjoyb** [comment]
Congratulations, @Amitooo1! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by Amitooo1** [comment]
@pooranjoyb can you please mark levels as per GSSOC if you also think this issue is valid?

**Comment by pooranjoyb** [comment]
Go ahead! @Amitooo1
