### ISSUE TITLE
Dark Mode Theme 

### ISSUE THREAD

**Issue by AkshatJangid787** [pooranjoyb/popShop#97]

**Comment by pooranjoyb** [comment]
Congratulations, @AkshatJangid787! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

**Comment by pooranjoyb** [comment]
No plans as of now :)
Happy Coding 🚀  @AkshatJangid787
